// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module GMI_Reduce (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        send_buf_V_address0,
        send_buf_V_ce0,
        send_buf_V_q0,
        recv_buf_V_address0,
        recv_buf_V_ce0,
        recv_buf_V_we0,
        recv_buf_V_d0,
        in_reduce_TDATA,
        in_reduce_TVALID,
        in_reduce_TREADY,
        in_reduce_TDEST,
        in_reduce_TLAST,
        in_reduce_TID,
        in_reduce_TUSER,
        in_reduce_TKEEP,
        out_reduce_TDATA,
        out_reduce_TVALID,
        out_reduce_TREADY,
        out_reduce_TDEST,
        out_reduce_TLAST,
        out_reduce_TID,
        out_reduce_TUSER,
        out_reduce_TKEEP
);

parameter    ap_ST_fsm_state1 = 20'd1;
parameter    ap_ST_fsm_state2 = 20'd2;
parameter    ap_ST_fsm_state3 = 20'd4;
parameter    ap_ST_fsm_state4 = 20'd8;
parameter    ap_ST_fsm_state5 = 20'd16;
parameter    ap_ST_fsm_state6 = 20'd32;
parameter    ap_ST_fsm_state7 = 20'd64;
parameter    ap_ST_fsm_state8 = 20'd128;
parameter    ap_ST_fsm_state9 = 20'd256;
parameter    ap_ST_fsm_state10 = 20'd512;
parameter    ap_ST_fsm_state11 = 20'd1024;
parameter    ap_ST_fsm_state12 = 20'd2048;
parameter    ap_ST_fsm_state13 = 20'd4096;
parameter    ap_ST_fsm_state14 = 20'd8192;
parameter    ap_ST_fsm_state15 = 20'd16384;
parameter    ap_ST_fsm_state16 = 20'd32768;
parameter    ap_ST_fsm_state17 = 20'd65536;
parameter    ap_ST_fsm_state18 = 20'd131072;
parameter    ap_ST_fsm_state19 = 20'd262144;
parameter    ap_ST_fsm_state20 = 20'd524288;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [42:0] p_read;
output  [6:0] send_buf_V_address0;
output   send_buf_V_ce0;
input  [63:0] send_buf_V_q0;
output  [6:0] recv_buf_V_address0;
output   recv_buf_V_ce0;
output   recv_buf_V_we0;
output  [63:0] recv_buf_V_d0;
input  [63:0] in_reduce_TDATA;
input   in_reduce_TVALID;
output   in_reduce_TREADY;
input  [7:0] in_reduce_TDEST;
input  [0:0] in_reduce_TLAST;
input  [7:0] in_reduce_TID;
input  [15:0] in_reduce_TUSER;
input  [7:0] in_reduce_TKEEP;
output  [63:0] out_reduce_TDATA;
output   out_reduce_TVALID;
input   out_reduce_TREADY;
output  [7:0] out_reduce_TDEST;
output  [0:0] out_reduce_TLAST;
output  [7:0] out_reduce_TID;
output  [15:0] out_reduce_TUSER;
output  [7:0] out_reduce_TKEEP;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[6:0] send_buf_V_address0;
reg send_buf_V_ce0;
reg recv_buf_V_ce0;
reg recv_buf_V_we0;
reg in_reduce_TREADY;
reg[63:0] out_reduce_TDATA;
reg out_reduce_TVALID;
reg[0:0] out_reduce_TLAST;
reg[7:0] out_reduce_TID;

(* fsm_encoding = "none" *) reg   [19:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [6:0] result_V_address0;
reg    result_V_ce0;
reg    result_V_we0;
reg   [63:0] result_V_d0;
wire   [63:0] result_V_q0;
reg    in_reduce_TDATA_blk_n;
wire    ap_CS_fsm_state7;
reg    out_reduce_TDATA_blk_n;
wire    ap_CS_fsm_state17;
wire   [0:0] grp_nbwritereq_fu_138_p8;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state14;
reg   [7:0] reg_336;
wire   [0:0] state_fu_351_p2;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln267_fu_378_p2;
wire   [0:0] icmp_ln879_fu_392_p2;
wire   [7:0] ID_file_NUM_OF_CHILD_fu_341_p4;
reg   [7:0] ID_file_NUM_OF_CHILD_reg_528;
reg   [0:0] state_reg_533;
wire   [7:0] pkt_out_id_V_fu_357_p1;
reg   [7:0] pkt_out_id_V_reg_537;
wire   [1:0] i_fu_367_p2;
reg   [1:0] i_reg_545;
wire    ap_CS_fsm_state2;
wire   [63:0] zext_ln263_fu_373_p1;
reg   [63:0] zext_ln263_reg_550;
wire   [0:0] icmp_ln261_fu_361_p2;
wire   [7:0] c_fu_383_p2;
reg   [7:0] c_reg_563;
wire   [7:0] pkt_out_id_V_2_fu_389_p1;
reg   [7:0] pkt_out_id_V_2_reg_568;
reg   [0:0] icmp_ln879_reg_573;
wire   [1:0] i_19_fu_404_p2;
reg   [1:0] i_19_reg_580;
wire    ap_CS_fsm_state5;
reg   [6:0] result_V_addr_2_reg_588;
wire    ap_CS_fsm_state6;
wire   [0:0] tmp_28_nbreadreq_fu_104_p8;
reg   [31:0] tmp_36_reg_603;
wire   [1:0] i_20_fu_465_p2;
reg   [1:0] i_20_reg_614;
wire    ap_CS_fsm_state12;
wire   [0:0] icmp_ln408_fu_459_p2;
wire   [0:0] pkt_out_last_V_1_fu_476_p2;
reg   [0:0] pkt_out_last_V_1_reg_624;
reg   [63:0] pkt_out_data_V_1_reg_629;
wire    ap_CS_fsm_state13;
wire   [1:0] i_18_fu_488_p2;
reg   [1:0] i_18_reg_640;
wire    ap_CS_fsm_state15;
wire   [63:0] zext_ln391_fu_494_p1;
reg   [63:0] zext_ln391_reg_645;
wire   [0:0] icmp_ln389_fu_482_p2;
wire   [1:0] i_17_fu_505_p2;
reg   [1:0] i_17_reg_661;
wire    ap_CS_fsm_state18;
wire   [0:0] icmp_ln243_fu_499_p2;
wire   [0:0] pkt_out_last_V_fu_516_p2;
reg   [0:0] pkt_out_last_V_reg_671;
reg   [63:0] pkt_out_data_V_reg_676;
wire    ap_CS_fsm_state19;
reg   [1:0] i_op_assign_5_reg_255;
wire    ap_CS_fsm_state3;
reg   [7:0] i_op_assign_6_reg_266;
wire   [0:0] icmp_ln269_fu_398_p2;
reg   [1:0] i_op_assign_7_reg_277;
wire    ap_CS_fsm_state10;
reg   [1:0] i_op_assign_9_reg_289;
reg    ap_block_state11_io;
reg    ap_block_state14_io;
reg   [1:0] i_op_assign_8_reg_300;
wire    ap_CS_fsm_state16;
reg   [1:0] i_op_assign_reg_311;
reg    ap_block_state17_io;
reg    ap_block_state20_io;
wire   [63:0] zext_ln275_fu_410_p1;
wire   [63:0] zext_ln410_fu_471_p1;
wire   [63:0] zext_ln245_fu_511_p1;
wire   [63:0] tmp1_fu_451_p3;
wire   [31:0] grp_fu_322_p0;
wire   [31:0] grp_fu_322_p1;
wire   [31:0] trunc_ln334_fu_419_p1;
wire   [31:0] trunc_ln334_1_fu_428_p1;
wire   [31:0] grp_fu_322_p2;
wire   [31:0] bitcast_ln334_2_fu_447_p1;
reg    grp_fu_322_ce;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg   [19:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 20'd1;
end

GMI_Reduce_result_V #(
    .DataWidth( 64 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
result_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(result_V_address0),
    .ce0(result_V_ce0),
    .we0(result_V_we0),
    .d0(result_V_d0),
    .q0(result_V_q0)
);

kernel_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
kernel_fadd_32ns_32ns_32_4_full_dsp_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_322_p0),
    .din1(grp_fu_322_p1),
    .ce(grp_fu_322_ce),
    .dout(grp_fu_322_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (state_fu_351_p2 == 1'd0))) begin
        i_op_assign_5_reg_255 <= 2'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        i_op_assign_5_reg_255 <= i_reg_545;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln261_fu_361_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i_op_assign_6_reg_266 <= 8'd0;
    end else if (((icmp_ln269_fu_398_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        i_op_assign_6_reg_266 <= c_reg_563;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln267_fu_378_p2 == 1'd0))) begin
        i_op_assign_7_reg_277 <= 2'd0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        i_op_assign_7_reg_277 <= i_19_reg_580;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln879_fu_392_p2 == 1'd1) & (icmp_ln267_fu_378_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        i_op_assign_8_reg_300 <= 2'd0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        i_op_assign_8_reg_300 <= i_18_reg_640;
    end
end

always @ (posedge ap_clk) begin
    if ((grp_nbwritereq_fu_138_p8 == 1'd1)) begin
        if (((1'b0 == ap_block_state14_io) & (1'b1 == ap_CS_fsm_state14))) begin
            i_op_assign_9_reg_289 <= i_20_reg_614;
        end else if (((1'b0 == ap_block_state11_io) & (1'b1 == ap_CS_fsm_state11))) begin
            i_op_assign_9_reg_289 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((grp_nbwritereq_fu_138_p8 == 1'd1)) begin
        if (((1'b0 == ap_block_state20_io) & (1'b1 == ap_CS_fsm_state20))) begin
            i_op_assign_reg_311 <= i_17_reg_661;
        end else if (((1'b0 == ap_block_state17_io) & (1'b1 == ap_CS_fsm_state17))) begin
            i_op_assign_reg_311 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ID_file_NUM_OF_CHILD_reg_528 <= {{p_read[42:35]}};
        state_reg_533 <= state_fu_351_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        c_reg_563 <= c_fu_383_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        i_17_reg_661 <= i_17_fu_505_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        i_18_reg_640 <= i_18_fu_488_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        i_19_reg_580 <= i_19_fu_404_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln879_reg_573 == 1'd0) & (state_reg_533 == 1'd0))) begin
        i_20_reg_614 <= i_20_fu_465_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_545 <= i_fu_367_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln267_fu_378_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        icmp_ln879_reg_573 <= icmp_ln879_fu_392_p2;
        pkt_out_id_V_2_reg_568 <= pkt_out_id_V_2_fu_389_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        pkt_out_data_V_1_reg_629 <= result_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        pkt_out_data_V_reg_676 <= send_buf_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((state_fu_351_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        pkt_out_id_V_reg_537 <= pkt_out_id_V_fu_357_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (icmp_ln408_fu_459_p2 == 1'd0) & (icmp_ln879_reg_573 == 1'd0) & (state_reg_533 == 1'd0))) begin
        pkt_out_last_V_1_reg_624 <= pkt_out_last_V_1_fu_476_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state18) & (icmp_ln243_fu_499_p2 == 1'd0))) begin
        pkt_out_last_V_reg_671 <= pkt_out_last_V_fu_516_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((state_fu_351_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((icmp_ln267_fu_378_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln879_fu_392_p2 == 1'd0)))) begin
        reg_336 <= {{p_read[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_28_nbreadreq_fu_104_p8 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        result_V_addr_2_reg_588[1 : 0] <= zext_ln275_fu_410_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((in_reduce_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        tmp_36_reg_603 <= {{result_V_q0[63:32]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln261_fu_361_p2 == 1'd0))) begin
        zext_ln263_reg_550[1 : 0] <= zext_ln263_fu_373_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state15) & (icmp_ln389_fu_482_p2 == 1'd0))) begin
        zext_ln391_reg_645[1 : 0] <= zext_ln391_fu_494_p1[1 : 0];
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state12) & ((state_reg_533 == 1'd1) | ((icmp_ln408_fu_459_p2 == 1'd1) | (icmp_ln879_reg_573 == 1'd1)))))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & ((state_reg_533 == 1'd1) | ((icmp_ln408_fu_459_p2 == 1'd1) | (icmp_ln879_reg_573 == 1'd1))))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state10) | ((in_reduce_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state7)))) begin
        grp_fu_322_ce = 1'b1;
    end else begin
        grp_fu_322_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        in_reduce_TDATA_blk_n = in_reduce_TVALID;
    end else begin
        in_reduce_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((in_reduce_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        in_reduce_TREADY = 1'b1;
    end else begin
        in_reduce_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((grp_nbwritereq_fu_138_p8 == 1'd1) & (1'b1 == ap_CS_fsm_state20))) begin
        out_reduce_TDATA = pkt_out_data_V_reg_676;
    end else if (((grp_nbwritereq_fu_138_p8 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        out_reduce_TDATA = pkt_out_data_V_1_reg_629;
    end else if ((((grp_nbwritereq_fu_138_p8 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((grp_nbwritereq_fu_138_p8 == 1'd1) & (1'b1 == ap_CS_fsm_state17)))) begin
        out_reduce_TDATA = 64'd253;
    end else begin
        out_reduce_TDATA = 'bx;
    end
end

always @ (*) begin
    if ((((grp_nbwritereq_fu_138_p8 == 1'd1) & (1'b1 == ap_CS_fsm_state14)) | ((grp_nbwritereq_fu_138_p8 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((grp_nbwritereq_fu_138_p8 == 1'd1) & (1'b1 == ap_CS_fsm_state20)) | ((grp_nbwritereq_fu_138_p8 == 1'd1) & (1'b1 == ap_CS_fsm_state17)))) begin
        out_reduce_TDATA_blk_n = out_reduce_TREADY;
    end else begin
        out_reduce_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((grp_nbwritereq_fu_138_p8 == 1'd1) & (1'b1 == ap_CS_fsm_state20)) | ((grp_nbwritereq_fu_138_p8 == 1'd1) & (1'b1 == ap_CS_fsm_state17)))) begin
        out_reduce_TID = pkt_out_id_V_reg_537;
    end else if ((((grp_nbwritereq_fu_138_p8 == 1'd1) & (1'b1 == ap_CS_fsm_state14)) | ((grp_nbwritereq_fu_138_p8 == 1'd1) & (1'b1 == ap_CS_fsm_state11)))) begin
        out_reduce_TID = pkt_out_id_V_2_reg_568;
    end else begin
        out_reduce_TID = 'bx;
    end
end

always @ (*) begin
    if (((grp_nbwritereq_fu_138_p8 == 1'd1) & (1'b1 == ap_CS_fsm_state20))) begin
        out_reduce_TLAST = pkt_out_last_V_reg_671;
    end else if (((grp_nbwritereq_fu_138_p8 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        out_reduce_TLAST = pkt_out_last_V_1_reg_624;
    end else if ((((grp_nbwritereq_fu_138_p8 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((grp_nbwritereq_fu_138_p8 == 1'd1) & (1'b1 == ap_CS_fsm_state17)))) begin
        out_reduce_TLAST = 1'd0;
    end else begin
        out_reduce_TLAST = 'bx;
    end
end

always @ (*) begin
    if ((((grp_nbwritereq_fu_138_p8 == 1'd1) & (1'b0 == ap_block_state14_io) & (1'b1 == ap_CS_fsm_state14)) | ((grp_nbwritereq_fu_138_p8 == 1'd1) & (1'b0 == ap_block_state11_io) & (1'b1 == ap_CS_fsm_state11)) | ((grp_nbwritereq_fu_138_p8 == 1'd1) & (1'b0 == ap_block_state20_io) & (1'b1 == ap_CS_fsm_state20)) | ((grp_nbwritereq_fu_138_p8 == 1'd1) & (1'b0 == ap_block_state17_io) & (1'b1 == ap_CS_fsm_state17)))) begin
        out_reduce_TVALID = 1'b1;
    end else begin
        out_reduce_TVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        recv_buf_V_ce0 = 1'b1;
    end else begin
        recv_buf_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        recv_buf_V_we0 = 1'b1;
    end else begin
        recv_buf_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        result_V_address0 = zext_ln391_fu_494_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        result_V_address0 = zext_ln410_fu_471_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        result_V_address0 = result_V_addr_2_reg_588;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        result_V_address0 = zext_ln275_fu_410_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        result_V_address0 = zext_ln263_reg_550;
    end else begin
        result_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state6))) begin
        result_V_ce0 = 1'b1;
    end else begin
        result_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        result_V_d0 = tmp1_fu_451_p3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        result_V_d0 = send_buf_V_q0;
    end else begin
        result_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state3))) begin
        result_V_we0 = 1'b1;
    end else begin
        result_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        send_buf_V_address0 = zext_ln245_fu_511_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        send_buf_V_address0 = zext_ln263_fu_373_p1;
    end else begin
        send_buf_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state2))) begin
        send_buf_V_ce0 = 1'b1;
    end else begin
        send_buf_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((state_fu_351_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (state_fu_351_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln261_fu_361_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln879_fu_392_p2 == 1'd1) & (icmp_ln267_fu_378_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else if (((icmp_ln267_fu_378_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln879_fu_392_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((icmp_ln269_fu_398_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((tmp_28_nbreadreq_fu_104_p8 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((in_reduce_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_nbwritereq_fu_138_p8 == 1'd1) & (1'b0 == ap_block_state11_io) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else if (((grp_nbwritereq_fu_138_p8 == 1'd0) & (1'b0 == ap_block_state11_io) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & ((state_reg_533 == 1'd1) | ((icmp_ln408_fu_459_p2 == 1'd1) | (icmp_ln879_reg_573 == 1'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((grp_nbwritereq_fu_138_p8 == 1'd1) & (1'b0 == ap_block_state14_io) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else if (((grp_nbwritereq_fu_138_p8 == 1'd0) & (1'b0 == ap_block_state14_io) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((icmp_ln389_fu_482_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state17 : begin
            if (((grp_nbwritereq_fu_138_p8 == 1'd1) & (1'b0 == ap_block_state17_io) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else if (((grp_nbwritereq_fu_138_p8 == 1'd0) & (1'b0 == ap_block_state17_io) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            if (((icmp_ln243_fu_499_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            if (((grp_nbwritereq_fu_138_p8 == 1'd1) & (1'b0 == ap_block_state20_io) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else if (((grp_nbwritereq_fu_138_p8 == 1'd0) & (1'b0 == ap_block_state20_io) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ID_file_NUM_OF_CHILD_fu_341_p4 = {{p_read[42:35]}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state11_io = ((grp_nbwritereq_fu_138_p8 == 1'd1) & (out_reduce_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state14_io = ((grp_nbwritereq_fu_138_p8 == 1'd1) & (out_reduce_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state17_io = ((grp_nbwritereq_fu_138_p8 == 1'd1) & (out_reduce_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state20_io = ((grp_nbwritereq_fu_138_p8 == 1'd1) & (out_reduce_TREADY == 1'b0));
end

assign bitcast_ln334_2_fu_447_p1 = grp_fu_322_p2;

assign c_fu_383_p2 = (i_op_assign_6_reg_266 + 8'd1);

assign grp_fu_322_p0 = trunc_ln334_fu_419_p1;

assign grp_fu_322_p1 = trunc_ln334_1_fu_428_p1;

assign grp_nbwritereq_fu_138_p8 = out_reduce_TREADY;

assign i_17_fu_505_p2 = (i_op_assign_reg_311 + 2'd1);

assign i_18_fu_488_p2 = (i_op_assign_8_reg_300 + 2'd1);

assign i_19_fu_404_p2 = (i_op_assign_7_reg_277 + 2'd1);

assign i_20_fu_465_p2 = (i_op_assign_9_reg_289 + 2'd1);

assign i_fu_367_p2 = (i_op_assign_5_reg_255 + 2'd1);

assign icmp_ln243_fu_499_p2 = ((i_op_assign_reg_311 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln261_fu_361_p2 = ((i_op_assign_5_reg_255 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln267_fu_378_p2 = ((i_op_assign_6_reg_266 == ID_file_NUM_OF_CHILD_reg_528) ? 1'b1 : 1'b0);

assign icmp_ln269_fu_398_p2 = ((i_op_assign_7_reg_277 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln389_fu_482_p2 = ((i_op_assign_8_reg_300 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln408_fu_459_p2 = ((i_op_assign_9_reg_289 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln879_fu_392_p2 = ((pkt_out_id_V_2_fu_389_p1 == 8'd0) ? 1'b1 : 1'b0);

assign out_reduce_TDEST = reg_336;

assign out_reduce_TKEEP = 8'd255;

assign out_reduce_TUSER = 16'd3;

assign pkt_out_id_V_2_fu_389_p1 = p_read[7:0];

assign pkt_out_id_V_fu_357_p1 = p_read[7:0];

assign pkt_out_last_V_1_fu_476_p2 = ((i_20_fu_465_p2 == 2'd2) ? 1'b1 : 1'b0);

assign pkt_out_last_V_fu_516_p2 = ((i_17_fu_505_p2 == 2'd2) ? 1'b1 : 1'b0);

assign recv_buf_V_address0 = zext_ln391_reg_645;

assign recv_buf_V_d0 = result_V_q0;

assign state_fu_351_p2 = ((ID_file_NUM_OF_CHILD_fu_341_p4 == 8'd0) ? 1'b1 : 1'b0);

assign tmp1_fu_451_p3 = {{tmp_36_reg_603}, {bitcast_ln334_2_fu_447_p1}};

assign tmp_28_nbreadreq_fu_104_p8 = in_reduce_TVALID;

assign trunc_ln334_1_fu_428_p1 = result_V_q0[31:0];

assign trunc_ln334_fu_419_p1 = in_reduce_TDATA[31:0];

assign zext_ln245_fu_511_p1 = i_op_assign_reg_311;

assign zext_ln263_fu_373_p1 = i_op_assign_5_reg_255;

assign zext_ln275_fu_410_p1 = i_op_assign_7_reg_277;

assign zext_ln391_fu_494_p1 = i_op_assign_8_reg_300;

assign zext_ln410_fu_471_p1 = i_op_assign_9_reg_289;

always @ (posedge ap_clk) begin
    zext_ln263_reg_550[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    result_V_addr_2_reg_588[6:2] <= 5'b00000;
    zext_ln391_reg_645[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
end

endmodule //GMI_Reduce
