// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module mul_bytes (
        ap_ready,
        a_V,
        b_V,
        ap_return
);


output   ap_ready;
input  [4:0] a_V;
input  [7:0] b_V;
output  [7:0] ap_return;

wire   [0:0] trunc_ln19_fu_66_p1;
wire   [3:0] trunc_ln19_1_fu_70_p1;
wire   [3:0] select_ln19_fu_74_p3;
wire   [0:0] tmp_fu_92_p3;
wire   [4:0] shl_ln841_fu_86_p2;
wire   [0:0] tmp_1_fu_116_p3;
wire   [5:0] shl_ln841_1_fu_108_p3;
wire   [5:0] select_ln19_2_fu_124_p3;
wire   [0:0] tmp_2_fu_144_p3;
wire   [6:0] shl_ln841_2_fu_136_p3;
wire   [0:0] tmp_3_fu_168_p3;
wire   [7:0] shl_ln841_3_fu_160_p3;
wire   [2:0] trunc_ln841_fu_184_p1;
wire   [7:0] shl_ln841_4_fu_188_p3;
wire   [0:0] tmp_4_fu_196_p3;
wire   [7:0] or_ln719_fu_204_p2;
wire   [0:0] tmp_5_fu_218_p3;
wire   [7:0] select_ln25_fu_210_p3;
wire   [7:0] shl_ln841_5_fu_234_p2;
wire   [0:0] tmp_6_fu_240_p3;
wire   [7:0] xor_ln719_fu_248_p2;
wire   [0:0] tmp_7_fu_262_p3;
wire   [7:0] select_ln25_1_fu_254_p3;
wire   [7:0] shl_ln841_6_fu_278_p2;
wire   [0:0] tmp_8_fu_284_p3;
wire   [7:0] xor_ln719_1_fu_292_p2;
wire   [0:0] tmp_9_fu_306_p3;
wire   [7:0] select_ln25_2_fu_298_p3;
wire   [4:0] zext_ln19_fu_82_p1;
wire   [4:0] select_ln19_1_fu_100_p3;
wire   [4:0] xor_ln19_fu_322_p2;
wire   [6:0] zext_ln19_1_fu_132_p1;
wire   [6:0] select_ln19_3_fu_152_p3;
wire   [6:0] xor_ln19_1_fu_332_p2;
wire   [6:0] zext_ln19_2_fu_328_p1;
wire   [6:0] xor_ln19_2_fu_338_p2;
wire   [7:0] select_ln19_4_fu_176_p3;
wire   [7:0] select_ln19_5_fu_226_p3;
wire   [7:0] select_ln19_6_fu_270_p3;
wire   [7:0] select_ln19_7_fu_314_p3;
wire   [7:0] xor_ln19_4_fu_354_p2;
wire   [7:0] xor_ln19_3_fu_348_p2;
wire   [7:0] xor_ln19_5_fu_360_p2;
wire   [7:0] zext_ln19_3_fu_344_p1;

assign ap_ready = 1'b1;

assign ap_return = (zext_ln19_3_fu_344_p1 ^ xor_ln19_5_fu_360_p2);

assign or_ln719_fu_204_p2 = (shl_ln841_4_fu_188_p3 | 8'd27);

assign select_ln19_1_fu_100_p3 = ((tmp_fu_92_p3[0:0] === 1'b1) ? shl_ln841_fu_86_p2 : 5'd0);

assign select_ln19_2_fu_124_p3 = ((tmp_1_fu_116_p3[0:0] === 1'b1) ? shl_ln841_1_fu_108_p3 : 6'd0);

assign select_ln19_3_fu_152_p3 = ((tmp_2_fu_144_p3[0:0] === 1'b1) ? shl_ln841_2_fu_136_p3 : 7'd0);

assign select_ln19_4_fu_176_p3 = ((tmp_3_fu_168_p3[0:0] === 1'b1) ? shl_ln841_3_fu_160_p3 : 8'd0);

assign select_ln19_5_fu_226_p3 = ((tmp_5_fu_218_p3[0:0] === 1'b1) ? select_ln25_fu_210_p3 : 8'd0);

assign select_ln19_6_fu_270_p3 = ((tmp_7_fu_262_p3[0:0] === 1'b1) ? select_ln25_1_fu_254_p3 : 8'd0);

assign select_ln19_7_fu_314_p3 = ((tmp_9_fu_306_p3[0:0] === 1'b1) ? select_ln25_2_fu_298_p3 : 8'd0);

assign select_ln19_fu_74_p3 = ((trunc_ln19_fu_66_p1[0:0] === 1'b1) ? trunc_ln19_1_fu_70_p1 : 4'd0);

assign select_ln25_1_fu_254_p3 = ((tmp_6_fu_240_p3[0:0] === 1'b1) ? xor_ln719_fu_248_p2 : shl_ln841_5_fu_234_p2);

assign select_ln25_2_fu_298_p3 = ((tmp_8_fu_284_p3[0:0] === 1'b1) ? xor_ln719_1_fu_292_p2 : shl_ln841_6_fu_278_p2);

assign select_ln25_fu_210_p3 = ((tmp_4_fu_196_p3[0:0] === 1'b1) ? or_ln719_fu_204_p2 : shl_ln841_4_fu_188_p3);

assign shl_ln841_1_fu_108_p3 = {{trunc_ln19_1_fu_70_p1}, {2'd0}};

assign shl_ln841_2_fu_136_p3 = {{trunc_ln19_1_fu_70_p1}, {3'd0}};

assign shl_ln841_3_fu_160_p3 = {{trunc_ln19_1_fu_70_p1}, {4'd0}};

assign shl_ln841_4_fu_188_p3 = {{trunc_ln841_fu_184_p1}, {5'd0}};

assign shl_ln841_5_fu_234_p2 = select_ln25_fu_210_p3 << 8'd1;

assign shl_ln841_6_fu_278_p2 = select_ln25_1_fu_254_p3 << 8'd1;

assign shl_ln841_fu_86_p2 = a_V << 5'd1;

assign tmp_1_fu_116_p3 = b_V[32'd2];

assign tmp_2_fu_144_p3 = b_V[32'd3];

assign tmp_3_fu_168_p3 = b_V[32'd4];

assign tmp_4_fu_196_p3 = a_V[32'd3];

assign tmp_5_fu_218_p3 = b_V[32'd5];

assign tmp_6_fu_240_p3 = select_ln25_fu_210_p3[32'd7];

assign tmp_7_fu_262_p3 = b_V[32'd6];

assign tmp_8_fu_284_p3 = select_ln25_1_fu_254_p3[32'd7];

assign tmp_9_fu_306_p3 = b_V[32'd7];

assign tmp_fu_92_p3 = b_V[32'd1];

assign trunc_ln19_1_fu_70_p1 = a_V[3:0];

assign trunc_ln19_fu_66_p1 = b_V[0:0];

assign trunc_ln841_fu_184_p1 = a_V[2:0];

assign xor_ln19_1_fu_332_p2 = (zext_ln19_1_fu_132_p1 ^ select_ln19_3_fu_152_p3);

assign xor_ln19_2_fu_338_p2 = (zext_ln19_2_fu_328_p1 ^ xor_ln19_1_fu_332_p2);

assign xor_ln19_3_fu_348_p2 = (select_ln19_5_fu_226_p3 ^ select_ln19_4_fu_176_p3);

assign xor_ln19_4_fu_354_p2 = (select_ln19_7_fu_314_p3 ^ select_ln19_6_fu_270_p3);

assign xor_ln19_5_fu_360_p2 = (xor_ln19_4_fu_354_p2 ^ xor_ln19_3_fu_348_p2);

assign xor_ln19_fu_322_p2 = (zext_ln19_fu_82_p1 ^ select_ln19_1_fu_100_p3);

assign xor_ln719_1_fu_292_p2 = (shl_ln841_6_fu_278_p2 ^ 8'd27);

assign xor_ln719_fu_248_p2 = (shl_ln841_5_fu_234_p2 ^ 8'd27);

assign zext_ln19_1_fu_132_p1 = select_ln19_2_fu_124_p3;

assign zext_ln19_2_fu_328_p1 = xor_ln19_fu_322_p2;

assign zext_ln19_3_fu_344_p1 = xor_ln19_2_fu_338_p2;

assign zext_ln19_fu_82_p1 = select_ln19_fu_74_p3;

endmodule //mul_bytes
