// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="broadcaster,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu19eg-ffvc1760-2-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.018000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=5,HLS_SYN_DSP=0,HLS_SYN_FF=213,HLS_SYN_LUT=419,HLS_VERSION=2019_1}" *)

module broadcaster (
        ap_clk,
        ap_rst_n,
        in_r_TDATA,
        in_r_TVALID,
        in_r_TREADY,
        in_r_TDEST,
        in_r_TLAST,
        in_r_TID,
        in_r_TUSER,
        in_r_TKEEP,
        out_r_TDATA,
        out_r_TVALID,
        out_r_TREADY,
        out_r_TDEST,
        out_r_TLAST,
        out_r_TID,
        out_r_TUSER,
        out_r_TKEEP
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst_n;
input  [63:0] in_r_TDATA;
input   in_r_TVALID;
output   in_r_TREADY;
input  [7:0] in_r_TDEST;
input  [0:0] in_r_TLAST;
input  [7:0] in_r_TID;
input  [15:0] in_r_TUSER;
input  [7:0] in_r_TKEEP;
output  [63:0] out_r_TDATA;
output   out_r_TVALID;
input   out_r_TREADY;
output  [7:0] out_r_TDEST;
output  [0:0] out_r_TLAST;
output  [7:0] out_r_TID;
output  [15:0] out_r_TUSER;
output  [7:0] out_r_TKEEP;

reg in_r_TREADY;
reg[63:0] out_r_TDATA;
reg out_r_TVALID;
reg[7:0] out_r_TDEST;
reg[0:0] out_r_TLAST;
reg[7:0] out_r_TID;
reg[15:0] out_r_TUSER;
reg[7:0] out_r_TKEEP;

 reg    ap_rst_n_inv;
reg   [4:0] ID_table_V_address0;
reg    ID_table_V_ce0;
wire   [3:0] ID_table_V_q0;
reg   [7:0] flit_count_V;
reg   [6:0] bcast_buffer_data_V_address0;
reg    bcast_buffer_data_V_ce0;
reg    bcast_buffer_data_V_we0;
wire   [63:0] bcast_buffer_data_V_q0;
reg   [6:0] bcast_buffer_last_V_address0;
reg    bcast_buffer_last_V_ce0;
reg    bcast_buffer_last_V_we0;
wire   [0:0] bcast_buffer_last_V_q0;
reg   [6:0] bcast_buffer_id_V_address0;
reg    bcast_buffer_id_V_ce0;
reg    bcast_buffer_id_V_we0;
wire   [7:0] bcast_buffer_id_V_q0;
reg   [6:0] bcast_buffer_user_V_address0;
reg    bcast_buffer_user_V_ce0;
reg    bcast_buffer_user_V_we0;
wire   [15:0] bcast_buffer_user_V_q0;
reg   [6:0] bcast_buffer_keep_V_address0;
reg    bcast_buffer_keep_V_ce0;
reg    bcast_buffer_keep_V_we0;
wire   [7:0] bcast_buffer_keep_V_q0;
reg    in_r_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] tmp_nbreadreq_fu_96_p8;
reg    out_r_TDATA_blk_n;
wire    ap_CS_fsm_state4;
wire   [0:0] grp_nbwritereq_fu_130_p8;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state2;
reg   [0:0] tmp_reg_498;
reg    ap_block_state1;
reg   [63:0] tmp_data_V_reg_502;
reg   [7:0] tmp_dest_V_1_reg_508;
reg   [0:0] tmp_last_V_reg_513;
reg   [7:0] tmp_id_V_reg_520;
reg   [15:0] tmp_user_V_reg_528;
reg   [7:0] tmp_keep_V_reg_534;
wire   [0:0] icmp_ln879_fu_366_p2;
reg   [0:0] icmp_ln879_reg_540;
reg   [4:0] ID_table_V_addr_1_reg_549;
wire   [5:0] zext_ln209_cast_fu_403_p3;
reg   [5:0] zext_ln209_cast_reg_557;
wire    ap_CS_fsm_state3;
wire  signed [7:0] pkt_in_dest_V_fu_411_p1;
reg  signed [7:0] pkt_in_dest_V_reg_562;
wire   [7:0] add_ln700_fu_428_p2;
reg   [7:0] add_ln700_reg_570;
reg    ap_block_state4_io;
wire  signed [8:0] sext_ln887_fu_444_p1;
reg  signed [8:0] sext_ln887_reg_579;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln887_fu_448_p2;
wire  signed [7:0] tmp_dest_V_2_fu_467_p1;
reg  signed [7:0] tmp_dest_V_2_reg_592;
wire    ap_CS_fsm_state7;
wire   [7:0] j_fu_476_p2;
reg   [7:0] j_reg_600;
wire    ap_CS_fsm_state8;
wire   [63:0] zext_ln824_fu_482_p1;
reg   [63:0] zext_ln824_reg_605;
wire   [0:0] icmp_ln822_fu_471_p2;
wire   [8:0] i_fu_486_p2;
wire    ap_CS_fsm_state9;
reg   [8:0] i_op_assign_reg_308;
reg   [7:0] i_op_assign_1_reg_320;
reg   [7:0] flit_count_V_new_0_reg_331;
wire   [0:0] and_ln818_fu_439_p2;
wire   [63:0] zext_ln209_fu_380_p1;
wire   [63:0] tmp_5_fu_391_p3;
wire   [63:0] zext_ln544_fu_419_p1;
wire   [63:0] zext_ln209_1_fu_462_p1;
wire    ap_CS_fsm_state11;
reg    ap_block_state2_io;
wire   [9:0] tmp_4_fu_372_p3;
wire   [9:0] or_ln895_fu_385_p2;
wire   [3:0] trunc_ln209_fu_400_p1;
wire   [0:0] icmp_ln895_fu_434_p2;
wire   [5:0] trunc_ln209_1_fu_453_p1;
wire   [5:0] add_ln209_fu_457_p2;
reg   [10:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 flit_count_V = 8'd0;
#0 ap_CS_fsm = 11'd1;
end

broadcaster_ID_table_V #(
    .DataWidth( 4 ),
    .AddressRange( 28 ),
    .AddressWidth( 5 ))
ID_table_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(ID_table_V_address0),
    .ce0(ID_table_V_ce0),
    .q0(ID_table_V_q0)
);

broadcaster_bcast_buffer_data_V #(
    .DataWidth( 64 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
bcast_buffer_data_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(bcast_buffer_data_V_address0),
    .ce0(bcast_buffer_data_V_ce0),
    .we0(bcast_buffer_data_V_we0),
    .d0(tmp_data_V_reg_502),
    .q0(bcast_buffer_data_V_q0)
);

broadcaster_bcast_buffer_last_V #(
    .DataWidth( 1 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
bcast_buffer_last_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(bcast_buffer_last_V_address0),
    .ce0(bcast_buffer_last_V_ce0),
    .we0(bcast_buffer_last_V_we0),
    .d0(tmp_last_V_reg_513),
    .q0(bcast_buffer_last_V_q0)
);

broadcaster_bcast_buffer_id_V #(
    .DataWidth( 8 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
bcast_buffer_id_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(bcast_buffer_id_V_address0),
    .ce0(bcast_buffer_id_V_ce0),
    .we0(bcast_buffer_id_V_we0),
    .d0(tmp_id_V_reg_520),
    .q0(bcast_buffer_id_V_q0)
);

broadcaster_bcast_buffer_user_V #(
    .DataWidth( 16 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
bcast_buffer_user_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(bcast_buffer_user_V_address0),
    .ce0(bcast_buffer_user_V_ce0),
    .we0(bcast_buffer_user_V_we0),
    .d0(tmp_user_V_reg_528),
    .q0(bcast_buffer_user_V_q0)
);

broadcaster_bcast_buffer_id_V #(
    .DataWidth( 8 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
bcast_buffer_keep_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(bcast_buffer_keep_V_address0),
    .ce0(bcast_buffer_keep_V_ce0),
    .we0(bcast_buffer_keep_V_we0),
    .d0(tmp_keep_V_reg_534),
    .q0(bcast_buffer_keep_V_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln887_fu_448_p2 == 1'd0))) begin
        flit_count_V_new_0_reg_331 <= 8'd0;
    end else if (((1'd0 == and_ln818_fu_439_p2) & (1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_io) & (grp_nbwritereq_fu_130_p8 == 1'd1))) begin
        flit_count_V_new_0_reg_331 <= add_ln700_fu_428_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        i_op_assign_1_reg_320 <= 8'd0;
    end else if (((out_r_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        i_op_assign_1_reg_320 <= j_reg_600;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        i_op_assign_reg_308 <= 9'd1;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln822_fu_471_p2 == 1'd1))) begin
        i_op_assign_reg_308 <= i_fu_486_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((in_r_TVALID == 1'b0) & (tmp_nbreadreq_fu_96_p8 == 1'd1)) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln879_fu_366_p2 == 1'd1) & (tmp_nbreadreq_fu_96_p8 == 1'd1))) begin
        ID_table_V_addr_1_reg_549[4 : 2] <= tmp_5_fu_391_p3[4 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_io) & (grp_nbwritereq_fu_130_p8 == 1'd1))) begin
        add_ln700_reg_570 <= add_ln700_fu_428_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln879_reg_540 == 1'd1) & (tmp_reg_498 == 1'd1))) begin
        flit_count_V <= flit_count_V_new_0_reg_331;
    end
end

always @ (posedge ap_clk) begin
    if ((~((in_r_TVALID == 1'b0) & (tmp_nbreadreq_fu_96_p8 == 1'd1)) & (1'b1 == ap_CS_fsm_state1) & (tmp_nbreadreq_fu_96_p8 == 1'd1))) begin
        icmp_ln879_reg_540 <= icmp_ln879_fu_366_p2;
        tmp_data_V_reg_502 <= in_r_TDATA;
        tmp_dest_V_1_reg_508 <= in_r_TDEST;
        tmp_id_V_reg_520 <= in_r_TID;
        tmp_keep_V_reg_534 <= in_r_TKEEP;
        tmp_last_V_reg_513 <= in_r_TLAST;
        tmp_user_V_reg_528 <= in_r_TUSER;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        j_reg_600 <= j_fu_476_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        pkt_in_dest_V_reg_562 <= pkt_in_dest_V_fu_411_p1;
        zext_ln209_cast_reg_557[5 : 2] <= zext_ln209_cast_fu_403_p3[5 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        sext_ln887_reg_579 <= sext_ln887_fu_444_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        tmp_dest_V_2_reg_592 <= tmp_dest_V_2_fu_467_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((in_r_TVALID == 1'b0) & (tmp_nbreadreq_fu_96_p8 == 1'd1)) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_reg_498 <= tmp_nbreadreq_fu_96_p8;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln822_fu_471_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        zext_ln824_reg_605[7 : 0] <= zext_ln824_fu_482_p1[7 : 0];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ID_table_V_address0 = zext_ln209_1_fu_462_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        ID_table_V_address0 = ID_table_V_addr_1_reg_549;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        ID_table_V_address0 = zext_ln209_fu_380_p1;
    end else begin
        ID_table_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | ((1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_io)) | (~((in_r_TVALID == 1'b0) & (tmp_nbreadreq_fu_96_p8 == 1'd1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        ID_table_V_ce0 = 1'b1;
    end else begin
        ID_table_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        bcast_buffer_data_V_address0 = zext_ln824_reg_605;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        bcast_buffer_data_V_address0 = zext_ln544_fu_419_p1;
    end else begin
        bcast_buffer_data_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_io)))) begin
        bcast_buffer_data_V_ce0 = 1'b1;
    end else begin
        bcast_buffer_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_io) & (grp_nbwritereq_fu_130_p8 == 1'd1))) begin
        bcast_buffer_data_V_we0 = 1'b1;
    end else begin
        bcast_buffer_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        bcast_buffer_id_V_address0 = zext_ln824_reg_605;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        bcast_buffer_id_V_address0 = zext_ln544_fu_419_p1;
    end else begin
        bcast_buffer_id_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_io)))) begin
        bcast_buffer_id_V_ce0 = 1'b1;
    end else begin
        bcast_buffer_id_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_io) & (grp_nbwritereq_fu_130_p8 == 1'd1))) begin
        bcast_buffer_id_V_we0 = 1'b1;
    end else begin
        bcast_buffer_id_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        bcast_buffer_keep_V_address0 = zext_ln824_reg_605;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        bcast_buffer_keep_V_address0 = zext_ln544_fu_419_p1;
    end else begin
        bcast_buffer_keep_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_io)))) begin
        bcast_buffer_keep_V_ce0 = 1'b1;
    end else begin
        bcast_buffer_keep_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_io) & (grp_nbwritereq_fu_130_p8 == 1'd1))) begin
        bcast_buffer_keep_V_we0 = 1'b1;
    end else begin
        bcast_buffer_keep_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        bcast_buffer_last_V_address0 = zext_ln824_reg_605;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        bcast_buffer_last_V_address0 = zext_ln544_fu_419_p1;
    end else begin
        bcast_buffer_last_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_io)))) begin
        bcast_buffer_last_V_ce0 = 1'b1;
    end else begin
        bcast_buffer_last_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_io) & (grp_nbwritereq_fu_130_p8 == 1'd1))) begin
        bcast_buffer_last_V_we0 = 1'b1;
    end else begin
        bcast_buffer_last_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        bcast_buffer_user_V_address0 = zext_ln824_reg_605;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        bcast_buffer_user_V_address0 = zext_ln544_fu_419_p1;
    end else begin
        bcast_buffer_user_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_io)))) begin
        bcast_buffer_user_V_ce0 = 1'b1;
    end else begin
        bcast_buffer_user_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_io) & (grp_nbwritereq_fu_130_p8 == 1'd1))) begin
        bcast_buffer_user_V_we0 = 1'b1;
    end else begin
        bcast_buffer_user_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (tmp_nbreadreq_fu_96_p8 == 1'd1))) begin
        in_r_TDATA_blk_n = in_r_TVALID;
    end else begin
        in_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((in_r_TVALID == 1'b0) & (tmp_nbreadreq_fu_96_p8 == 1'd1)) & (1'b1 == ap_CS_fsm_state1) & (tmp_nbreadreq_fu_96_p8 == 1'd1))) begin
        in_r_TREADY = 1'b1;
    end else begin
        in_r_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        out_r_TDATA = bcast_buffer_data_V_q0;
    end else if ((((1'b1 == ap_CS_fsm_state2) & (grp_nbwritereq_fu_130_p8 == 1'd1)) | ((1'b1 == ap_CS_fsm_state4) & (grp_nbwritereq_fu_130_p8 == 1'd1)))) begin
        out_r_TDATA = tmp_data_V_reg_502;
    end else begin
        out_r_TDATA = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state2) & (grp_nbwritereq_fu_130_p8 == 1'd1)) | ((1'b1 == ap_CS_fsm_state4) & (grp_nbwritereq_fu_130_p8 == 1'd1)))) begin
        out_r_TDATA_blk_n = out_r_TREADY;
    end else begin
        out_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        out_r_TDEST = tmp_dest_V_2_reg_592;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_nbwritereq_fu_130_p8 == 1'd1))) begin
        out_r_TDEST = pkt_in_dest_V_reg_562;
    end else if (((1'b1 == ap_CS_fsm_state2) & (grp_nbwritereq_fu_130_p8 == 1'd1))) begin
        out_r_TDEST = tmp_dest_V_1_reg_508;
    end else begin
        out_r_TDEST = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        out_r_TID = bcast_buffer_id_V_q0;
    end else if ((((1'b1 == ap_CS_fsm_state2) & (grp_nbwritereq_fu_130_p8 == 1'd1)) | ((1'b1 == ap_CS_fsm_state4) & (grp_nbwritereq_fu_130_p8 == 1'd1)))) begin
        out_r_TID = tmp_id_V_reg_520;
    end else begin
        out_r_TID = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        out_r_TKEEP = bcast_buffer_keep_V_q0;
    end else if ((((1'b1 == ap_CS_fsm_state2) & (grp_nbwritereq_fu_130_p8 == 1'd1)) | ((1'b1 == ap_CS_fsm_state4) & (grp_nbwritereq_fu_130_p8 == 1'd1)))) begin
        out_r_TKEEP = tmp_keep_V_reg_534;
    end else begin
        out_r_TKEEP = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        out_r_TLAST = bcast_buffer_last_V_q0;
    end else if ((((1'b1 == ap_CS_fsm_state2) & (grp_nbwritereq_fu_130_p8 == 1'd1)) | ((1'b1 == ap_CS_fsm_state4) & (grp_nbwritereq_fu_130_p8 == 1'd1)))) begin
        out_r_TLAST = tmp_last_V_reg_513;
    end else begin
        out_r_TLAST = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        out_r_TUSER = bcast_buffer_user_V_q0;
    end else if ((((1'b1 == ap_CS_fsm_state2) & (grp_nbwritereq_fu_130_p8 == 1'd1)) | ((1'b1 == ap_CS_fsm_state4) & (grp_nbwritereq_fu_130_p8 == 1'd1)))) begin
        out_r_TUSER = tmp_user_V_reg_528;
    end else begin
        out_r_TUSER = 'bx;
    end
end

always @ (*) begin
    if ((((out_r_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state10)) | ((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2) & (grp_nbwritereq_fu_130_p8 == 1'd1)) | ((1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_io) & (grp_nbwritereq_fu_130_p8 == 1'd1)))) begin
        out_r_TVALID = 1'b1;
    end else begin
        out_r_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((in_r_TVALID == 1'b0) & (tmp_nbreadreq_fu_96_p8 == 1'd1)) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln879_fu_366_p2 == 1'd0) & (tmp_nbreadreq_fu_96_p8 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if ((~((in_r_TVALID == 1'b0) & (tmp_nbreadreq_fu_96_p8 == 1'd1)) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln879_fu_366_p2 == 1'd1) & (tmp_nbreadreq_fu_96_p8 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if ((~((in_r_TVALID == 1'b0) & (tmp_nbreadreq_fu_96_p8 == 1'd1)) & (1'b1 == ap_CS_fsm_state1) & (tmp_nbreadreq_fu_96_p8 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2) & (grp_nbwritereq_fu_130_p8 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else if (((1'b0 == ap_block_state2_io) & (1'b1 == ap_CS_fsm_state2) & (grp_nbwritereq_fu_130_p8 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'd0 == and_ln818_fu_439_p2) & (1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_io) & (grp_nbwritereq_fu_130_p8 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else if (((1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_io) & (1'd1 == and_ln818_fu_439_p2) & (grp_nbwritereq_fu_130_p8 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if (((1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_io) & (grp_nbwritereq_fu_130_p8 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln887_fu_448_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln822_fu_471_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (grp_nbwritereq_fu_130_p8 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((out_r_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln209_fu_457_p2 = (trunc_ln209_1_fu_453_p1 + zext_ln209_cast_reg_557);

assign add_ln700_fu_428_p2 = (flit_count_V + 8'd1);

assign and_ln818_fu_439_p2 = (tmp_last_V_reg_513 & icmp_ln895_fu_434_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((in_r_TVALID == 1'b0) & (tmp_nbreadreq_fu_96_p8 == 1'd1));
end

always @ (*) begin
    ap_block_state2_io = ((out_r_TREADY == 1'b0) & (grp_nbwritereq_fu_130_p8 == 1'd1));
end

always @ (*) begin
    ap_block_state4_io = ((out_r_TREADY == 1'b0) & (grp_nbwritereq_fu_130_p8 == 1'd1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_nbwritereq_fu_130_p8 = out_r_TREADY;

assign i_fu_486_p2 = (i_op_assign_reg_308 + 9'd1);

assign icmp_ln822_fu_471_p2 = ((i_op_assign_1_reg_320 == add_ln700_reg_570) ? 1'b1 : 1'b0);

assign icmp_ln879_fu_366_p2 = ((in_r_TDEST == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln887_fu_448_p2 = ((i_op_assign_reg_308 < sext_ln887_reg_579) ? 1'b1 : 1'b0);

assign icmp_ln895_fu_434_p2 = ((tmp_id_V_reg_520 < 8'd3) ? 1'b1 : 1'b0);

assign j_fu_476_p2 = (i_op_assign_1_reg_320 + 8'd1);

assign or_ln895_fu_385_p2 = (tmp_4_fu_372_p3 | 10'd3);

assign pkt_in_dest_V_fu_411_p1 = $signed(ID_table_V_q0);

assign sext_ln887_fu_444_p1 = $signed(ID_table_V_q0);

assign tmp_4_fu_372_p3 = {{in_r_TID}, {2'd0}};

assign tmp_5_fu_391_p3 = {{54'd0}, {or_ln895_fu_385_p2}};

assign tmp_dest_V_2_fu_467_p1 = $signed(ID_table_V_q0);

assign tmp_nbreadreq_fu_96_p8 = in_r_TVALID;

assign trunc_ln209_1_fu_453_p1 = i_op_assign_reg_308[5:0];

assign trunc_ln209_fu_400_p1 = tmp_id_V_reg_520[3:0];

assign zext_ln209_1_fu_462_p1 = add_ln209_fu_457_p2;

assign zext_ln209_cast_fu_403_p3 = {{trunc_ln209_fu_400_p1}, {2'd0}};

assign zext_ln209_fu_380_p1 = tmp_4_fu_372_p3;

assign zext_ln544_fu_419_p1 = flit_count_V;

assign zext_ln824_fu_482_p1 = i_op_assign_1_reg_320;

always @ (posedge ap_clk) begin
    ID_table_V_addr_1_reg_549[1:0] <= 2'b11;
    zext_ln209_cast_reg_557[1:0] <= 2'b00;
    zext_ln824_reg_605[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
end

endmodule //broadcaster
