// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="galapagos_bridge,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu19eg-ffvc1760-2-i,HLS_INPUT_CLOCK=3.103000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=1.102000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=6044,HLS_SYN_LUT=972,HLS_VERSION=2019_1}" *)

module galapagos_bridge (
        g2N_input_TDATA,
        g2N_input_TDEST,
        g2N_input_TLAST,
        g2N_input_TID,
        g2N_input_TUSER,
        g2N_input_TKEEP,
        g2N_output_TDATA,
        g2N_output_TKEEP,
        g2N_output_TLAST,
        g2N_output_TUSER,
        n2G_input_TDATA,
        n2G_input_TKEEP,
        n2G_input_TLAST,
        n2G_input_TUSER,
        n2G_output_TDATA,
        n2G_output_TDEST,
        n2G_output_TLAST,
        n2G_output_TID,
        n2G_output_TUSER,
        n2G_output_TKEEP,
        ap_clk,
        ap_rst_n,
        g2N_input_TVALID,
        g2N_input_TREADY,
        g2N_output_TVALID,
        g2N_output_TREADY,
        n2G_input_TVALID,
        n2G_input_TREADY,
        n2G_output_TVALID,
        n2G_output_TREADY
);


input  [511:0] g2N_input_TDATA;
input  [7:0] g2N_input_TDEST;
input  [0:0] g2N_input_TLAST;
input  [7:0] g2N_input_TID;
input  [15:0] g2N_input_TUSER;
input  [63:0] g2N_input_TKEEP;
output  [511:0] g2N_output_TDATA;
output  [63:0] g2N_output_TKEEP;
output  [0:0] g2N_output_TLAST;
output  [15:0] g2N_output_TUSER;
input  [511:0] n2G_input_TDATA;
input  [63:0] n2G_input_TKEEP;
input  [0:0] n2G_input_TLAST;
input  [15:0] n2G_input_TUSER;
output  [511:0] n2G_output_TDATA;
output  [7:0] n2G_output_TDEST;
output  [0:0] n2G_output_TLAST;
output  [7:0] n2G_output_TID;
output  [15:0] n2G_output_TUSER;
output  [63:0] n2G_output_TKEEP;
input   ap_clk;
input   ap_rst_n;
input   g2N_input_TVALID;
output   g2N_input_TREADY;
output   g2N_output_TVALID;
input   g2N_output_TREADY;
input   n2G_input_TVALID;
output   n2G_input_TREADY;
output   n2G_output_TVALID;
input   n2G_output_TREADY;

 reg    ap_rst_n_inv;
wire    g2N_U0_ap_start;
wire    g2N_U0_ap_done;
wire    g2N_U0_ap_continue;
wire    g2N_U0_ap_idle;
wire    g2N_U0_ap_ready;
wire    g2N_U0_g2N_input_TREADY;
wire   [511:0] g2N_U0_g2N_output_TDATA;
wire    g2N_U0_g2N_output_TVALID;
wire   [63:0] g2N_U0_g2N_output_TKEEP;
wire   [0:0] g2N_U0_g2N_output_TLAST;
wire   [15:0] g2N_U0_g2N_output_TUSER;
wire    ap_sync_continue;
wire    n2G_U0_ap_start;
wire    n2G_U0_ap_done;
wire    n2G_U0_ap_continue;
wire    n2G_U0_ap_idle;
wire    n2G_U0_ap_ready;
wire    n2G_U0_n2G_input_TREADY;
wire   [511:0] n2G_U0_n2G_output_TDATA;
wire    n2G_U0_n2G_output_TVALID;
wire   [7:0] n2G_U0_n2G_output_TDEST;
wire   [0:0] n2G_U0_n2G_output_TLAST;
wire   [7:0] n2G_U0_n2G_output_TID;
wire   [15:0] n2G_U0_n2G_output_TUSER;
wire   [63:0] n2G_U0_n2G_output_TKEEP;
wire    g2N_U0_start_full_n;
wire    g2N_U0_start_write;
wire    n2G_U0_start_full_n;
wire    n2G_U0_start_write;

g2N g2N_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(g2N_U0_ap_start),
    .ap_done(g2N_U0_ap_done),
    .ap_continue(g2N_U0_ap_continue),
    .ap_idle(g2N_U0_ap_idle),
    .ap_ready(g2N_U0_ap_ready),
    .g2N_input_TDATA(g2N_input_TDATA),
    .g2N_input_TVALID(g2N_input_TVALID),
    .g2N_input_TREADY(g2N_U0_g2N_input_TREADY),
    .g2N_input_TDEST(g2N_input_TDEST),
    .g2N_input_TLAST(g2N_input_TLAST),
    .g2N_input_TID(g2N_input_TID),
    .g2N_input_TUSER(g2N_input_TUSER),
    .g2N_input_TKEEP(g2N_input_TKEEP),
    .g2N_output_TDATA(g2N_U0_g2N_output_TDATA),
    .g2N_output_TVALID(g2N_U0_g2N_output_TVALID),
    .g2N_output_TREADY(g2N_output_TREADY),
    .g2N_output_TKEEP(g2N_U0_g2N_output_TKEEP),
    .g2N_output_TLAST(g2N_U0_g2N_output_TLAST),
    .g2N_output_TUSER(g2N_U0_g2N_output_TUSER)
);

n2G n2G_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(n2G_U0_ap_start),
    .ap_done(n2G_U0_ap_done),
    .ap_continue(n2G_U0_ap_continue),
    .ap_idle(n2G_U0_ap_idle),
    .ap_ready(n2G_U0_ap_ready),
    .n2G_input_TDATA(n2G_input_TDATA),
    .n2G_input_TVALID(n2G_input_TVALID),
    .n2G_input_TREADY(n2G_U0_n2G_input_TREADY),
    .n2G_input_TKEEP(n2G_input_TKEEP),
    .n2G_input_TLAST(n2G_input_TLAST),
    .n2G_input_TUSER(n2G_input_TUSER),
    .n2G_output_TDATA(n2G_U0_n2G_output_TDATA),
    .n2G_output_TVALID(n2G_U0_n2G_output_TVALID),
    .n2G_output_TREADY(n2G_output_TREADY),
    .n2G_output_TDEST(n2G_U0_n2G_output_TDEST),
    .n2G_output_TLAST(n2G_U0_n2G_output_TLAST),
    .n2G_output_TID(n2G_U0_n2G_output_TID),
    .n2G_output_TUSER(n2G_U0_n2G_output_TUSER),
    .n2G_output_TKEEP(n2G_U0_n2G_output_TKEEP)
);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b0;

assign g2N_U0_ap_continue = 1'b1;

assign g2N_U0_ap_start = 1'b1;

assign g2N_U0_start_full_n = 1'b1;

assign g2N_U0_start_write = 1'b0;

assign g2N_input_TREADY = g2N_U0_g2N_input_TREADY;

assign g2N_output_TDATA = g2N_U0_g2N_output_TDATA;

assign g2N_output_TKEEP = g2N_U0_g2N_output_TKEEP;

assign g2N_output_TLAST = g2N_U0_g2N_output_TLAST;

assign g2N_output_TUSER = g2N_U0_g2N_output_TUSER;

assign g2N_output_TVALID = g2N_U0_g2N_output_TVALID;

assign n2G_U0_ap_continue = 1'b1;

assign n2G_U0_ap_start = 1'b1;

assign n2G_U0_start_full_n = 1'b1;

assign n2G_U0_start_write = 1'b0;

assign n2G_input_TREADY = n2G_U0_n2G_input_TREADY;

assign n2G_output_TDATA = n2G_U0_n2G_output_TDATA;

assign n2G_output_TDEST = n2G_U0_n2G_output_TDEST;

assign n2G_output_TID = n2G_U0_n2G_output_TID;

assign n2G_output_TKEEP = n2G_U0_n2G_output_TKEEP;

assign n2G_output_TLAST = n2G_U0_n2G_output_TLAST;

assign n2G_output_TUSER = n2G_U0_n2G_output_TUSER;

assign n2G_output_TVALID = n2G_U0_n2G_output_TVALID;

endmodule //galapagos_bridge
