// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module n2G (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        n2G_input_TDATA,
        n2G_input_TVALID,
        n2G_input_TREADY,
        n2G_input_TKEEP,
        n2G_input_TLAST,
        n2G_input_TUSER,
        n2G_output_TDATA,
        n2G_output_TVALID,
        n2G_output_TREADY,
        n2G_output_TDEST,
        n2G_output_TLAST,
        n2G_output_TID,
        n2G_output_TUSER,
        n2G_output_TKEEP
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state5 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [511:0] n2G_input_TDATA;
input   n2G_input_TVALID;
output   n2G_input_TREADY;
input  [63:0] n2G_input_TKEEP;
input  [0:0] n2G_input_TLAST;
input  [15:0] n2G_input_TUSER;
output  [511:0] n2G_output_TDATA;
output   n2G_output_TVALID;
input   n2G_output_TREADY;
output  [7:0] n2G_output_TDEST;
output  [0:0] n2G_output_TLAST;
output  [7:0] n2G_output_TID;
output  [15:0] n2G_output_TUSER;
output  [63:0] n2G_output_TKEEP;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [511:0] input_V_data_V_0_data_out;
wire    input_V_data_V_0_vld_in;
wire    input_V_data_V_0_vld_out;
wire    input_V_data_V_0_ack_in;
reg    input_V_data_V_0_ack_out;
reg   [511:0] input_V_data_V_0_payload_A;
reg   [511:0] input_V_data_V_0_payload_B;
reg    input_V_data_V_0_sel_rd;
reg    input_V_data_V_0_sel_wr;
wire    input_V_data_V_0_sel;
wire    input_V_data_V_0_load_A;
wire    input_V_data_V_0_load_B;
reg   [1:0] input_V_data_V_0_state;
wire    input_V_data_V_0_state_cmp_full;
reg   [63:0] input_V_keep_V_0_data_out;
wire    input_V_keep_V_0_vld_in;
wire    input_V_keep_V_0_vld_out;
wire    input_V_keep_V_0_ack_in;
reg    input_V_keep_V_0_ack_out;
reg   [63:0] input_V_keep_V_0_payload_A;
reg   [63:0] input_V_keep_V_0_payload_B;
reg    input_V_keep_V_0_sel_rd;
reg    input_V_keep_V_0_sel_wr;
wire    input_V_keep_V_0_sel;
wire    input_V_keep_V_0_load_A;
wire    input_V_keep_V_0_load_B;
reg   [1:0] input_V_keep_V_0_state;
wire    input_V_keep_V_0_state_cmp_full;
reg   [0:0] input_V_last_V_0_data_out;
wire    input_V_last_V_0_vld_in;
wire    input_V_last_V_0_vld_out;
wire    input_V_last_V_0_ack_in;
reg    input_V_last_V_0_ack_out;
reg   [0:0] input_V_last_V_0_payload_A;
reg   [0:0] input_V_last_V_0_payload_B;
reg    input_V_last_V_0_sel_rd;
reg    input_V_last_V_0_sel_wr;
wire    input_V_last_V_0_sel;
wire    input_V_last_V_0_load_A;
wire    input_V_last_V_0_load_B;
reg   [1:0] input_V_last_V_0_state;
wire    input_V_last_V_0_state_cmp_full;
wire    input_V_user_V_0_vld_in;
reg    input_V_user_V_0_ack_out;
reg   [1:0] input_V_user_V_0_state;
reg   [511:0] output_V_data_V_1_data_out;
reg    output_V_data_V_1_vld_in;
wire    output_V_data_V_1_vld_out;
wire    output_V_data_V_1_ack_in;
wire    output_V_data_V_1_ack_out;
reg   [511:0] output_V_data_V_1_payload_A;
reg   [511:0] output_V_data_V_1_payload_B;
reg    output_V_data_V_1_sel_rd;
reg    output_V_data_V_1_sel_wr;
wire    output_V_data_V_1_sel;
wire    output_V_data_V_1_load_A;
wire    output_V_data_V_1_load_B;
reg   [1:0] output_V_data_V_1_state;
wire    output_V_data_V_1_state_cmp_full;
reg   [7:0] output_V_dest_V_1_data_out;
reg    output_V_dest_V_1_vld_in;
wire    output_V_dest_V_1_vld_out;
wire    output_V_dest_V_1_ack_in;
wire    output_V_dest_V_1_ack_out;
reg   [7:0] output_V_dest_V_1_payload_A;
reg   [7:0] output_V_dest_V_1_payload_B;
reg    output_V_dest_V_1_sel_rd;
reg    output_V_dest_V_1_sel_wr;
wire    output_V_dest_V_1_sel;
wire    output_V_dest_V_1_load_A;
wire    output_V_dest_V_1_load_B;
reg   [1:0] output_V_dest_V_1_state;
wire    output_V_dest_V_1_state_cmp_full;
reg   [0:0] output_V_last_V_1_data_out;
reg    output_V_last_V_1_vld_in;
wire    output_V_last_V_1_vld_out;
wire    output_V_last_V_1_ack_in;
wire    output_V_last_V_1_ack_out;
reg   [0:0] output_V_last_V_1_payload_A;
reg   [0:0] output_V_last_V_1_payload_B;
reg    output_V_last_V_1_sel_rd;
reg    output_V_last_V_1_sel_wr;
wire    output_V_last_V_1_sel;
wire    output_V_last_V_1_load_A;
wire    output_V_last_V_1_load_B;
reg   [1:0] output_V_last_V_1_state;
wire    output_V_last_V_1_state_cmp_full;
reg   [7:0] output_V_id_V_1_data_out;
reg    output_V_id_V_1_vld_in;
wire    output_V_id_V_1_vld_out;
wire    output_V_id_V_1_ack_in;
wire    output_V_id_V_1_ack_out;
reg   [7:0] output_V_id_V_1_payload_A;
reg   [7:0] output_V_id_V_1_payload_B;
reg    output_V_id_V_1_sel_rd;
reg    output_V_id_V_1_sel_wr;
wire    output_V_id_V_1_sel;
wire    output_V_id_V_1_load_A;
wire    output_V_id_V_1_load_B;
reg   [1:0] output_V_id_V_1_state;
wire    output_V_id_V_1_state_cmp_full;
reg   [15:0] output_V_user_V_1_data_out;
reg    output_V_user_V_1_vld_in;
wire    output_V_user_V_1_vld_out;
wire    output_V_user_V_1_ack_in;
wire    output_V_user_V_1_ack_out;
reg   [15:0] output_V_user_V_1_payload_A;
reg   [15:0] output_V_user_V_1_payload_B;
reg    output_V_user_V_1_sel_rd;
reg    output_V_user_V_1_sel_wr;
wire    output_V_user_V_1_sel;
wire    output_V_user_V_1_load_A;
wire    output_V_user_V_1_load_B;
reg   [1:0] output_V_user_V_1_state;
wire    output_V_user_V_1_state_cmp_full;
reg   [63:0] output_V_keep_V_1_data_out;
reg    output_V_keep_V_1_vld_in;
wire    output_V_keep_V_1_vld_out;
wire    output_V_keep_V_1_ack_in;
wire    output_V_keep_V_1_ack_out;
reg   [63:0] output_V_keep_V_1_payload_A;
reg   [63:0] output_V_keep_V_1_payload_B;
reg    output_V_keep_V_1_sel_rd;
reg    output_V_keep_V_1_sel_wr;
wire    output_V_keep_V_1_sel;
wire    output_V_keep_V_1_load_A;
wire    output_V_keep_V_1_load_B;
reg   [1:0] output_V_keep_V_1_state;
wire    output_V_keep_V_1_state_cmp_full;
reg    n2G_input_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln69_fu_137_p2;
reg    n2G_output_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] icmp_ln69_reg_172;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] icmp_ln69_reg_172_pp0_iter1_reg;
reg   [15:0] i_op_assign_reg_98;
reg   [7:0] id_V_reg_156;
reg    ap_block_state1;
reg   [7:0] dest_V_reg_161;
wire   [15:0] size_V_fu_133_p1;
reg   [15:0] size_V_reg_166;
reg    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_state3_io;
wire    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_state4_io;
reg    ap_block_pp0_stage0_11001;
wire   [15:0] i_fu_142_p2;
reg   [511:0] tmp_data_V_reg_181;
reg   [63:0] tmp_keep_V_reg_186;
reg   [0:0] tmp_last_V_reg_191;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_block_pp0_stage0_01001;
wire    ap_CS_fsm_state5;
reg    ap_block_state5;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 input_V_data_V_0_sel_rd = 1'b0;
#0 input_V_data_V_0_sel_wr = 1'b0;
#0 input_V_data_V_0_state = 2'd0;
#0 input_V_keep_V_0_sel_rd = 1'b0;
#0 input_V_keep_V_0_sel_wr = 1'b0;
#0 input_V_keep_V_0_state = 2'd0;
#0 input_V_last_V_0_sel_rd = 1'b0;
#0 input_V_last_V_0_sel_wr = 1'b0;
#0 input_V_last_V_0_state = 2'd0;
#0 input_V_user_V_0_state = 2'd0;
#0 output_V_data_V_1_sel_rd = 1'b0;
#0 output_V_data_V_1_sel_wr = 1'b0;
#0 output_V_data_V_1_state = 2'd0;
#0 output_V_dest_V_1_sel_rd = 1'b0;
#0 output_V_dest_V_1_sel_wr = 1'b0;
#0 output_V_dest_V_1_state = 2'd0;
#0 output_V_last_V_1_sel_rd = 1'b0;
#0 output_V_last_V_1_sel_wr = 1'b0;
#0 output_V_last_V_1_state = 2'd0;
#0 output_V_id_V_1_sel_rd = 1'b0;
#0 output_V_id_V_1_sel_wr = 1'b0;
#0 output_V_id_V_1_state = 2'd0;
#0 output_V_user_V_1_sel_rd = 1'b0;
#0 output_V_user_V_1_sel_wr = 1'b0;
#0 output_V_user_V_1_state = 2'd0;
#0 output_V_keep_V_1_sel_rd = 1'b0;
#0 output_V_keep_V_1_sel_wr = 1'b0;
#0 output_V_keep_V_1_state = 2'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((output_V_keep_V_1_state == 2'd1) | (output_V_user_V_1_state == 2'd1) | (output_V_id_V_1_state == 2'd1) | (output_V_last_V_1_state == 2'd1) | (output_V_dest_V_1_state == 2'd1) | (output_V_data_V_1_state == 2'd1) | ((output_V_keep_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0)) | ((output_V_user_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0)) | ((output_V_id_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0)) | ((output_V_last_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0)) | ((output_V_dest_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0)) | ((output_V_data_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0))) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (input_V_data_V_0_vld_out == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((~((ap_start == 1'b0) | (input_V_data_V_0_vld_out == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        input_V_data_V_0_sel_rd <= 1'b0;
    end else begin
        if (((input_V_data_V_0_ack_out == 1'b1) & (input_V_data_V_0_vld_out == 1'b1))) begin
            input_V_data_V_0_sel_rd <= ~input_V_data_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        input_V_data_V_0_sel_wr <= 1'b0;
    end else begin
        if (((input_V_data_V_0_ack_in == 1'b1) & (input_V_data_V_0_vld_in == 1'b1))) begin
            input_V_data_V_0_sel_wr <= ~input_V_data_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        input_V_data_V_0_state <= 2'd0;
    end else begin
        if ((((input_V_data_V_0_state == 2'd2) & (input_V_data_V_0_vld_in == 1'b0)) | ((input_V_data_V_0_state == 2'd3) & (input_V_data_V_0_vld_in == 1'b0) & (input_V_data_V_0_ack_out == 1'b1)))) begin
            input_V_data_V_0_state <= 2'd2;
        end else if ((((input_V_data_V_0_state == 2'd1) & (input_V_data_V_0_ack_out == 1'b0)) | ((input_V_data_V_0_state == 2'd3) & (input_V_data_V_0_ack_out == 1'b0) & (input_V_data_V_0_vld_in == 1'b1)))) begin
            input_V_data_V_0_state <= 2'd1;
        end else if (((~((input_V_data_V_0_vld_in == 1'b0) & (input_V_data_V_0_ack_out == 1'b1)) & ~((input_V_data_V_0_ack_out == 1'b0) & (input_V_data_V_0_vld_in == 1'b1)) & (input_V_data_V_0_state == 2'd3)) | ((input_V_data_V_0_state == 2'd1) & (input_V_data_V_0_ack_out == 1'b1)) | ((input_V_data_V_0_state == 2'd2) & (input_V_data_V_0_vld_in == 1'b1)))) begin
            input_V_data_V_0_state <= 2'd3;
        end else begin
            input_V_data_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        input_V_keep_V_0_sel_rd <= 1'b0;
    end else begin
        if (((input_V_keep_V_0_ack_out == 1'b1) & (input_V_keep_V_0_vld_out == 1'b1))) begin
            input_V_keep_V_0_sel_rd <= ~input_V_keep_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        input_V_keep_V_0_sel_wr <= 1'b0;
    end else begin
        if (((input_V_keep_V_0_ack_in == 1'b1) & (input_V_keep_V_0_vld_in == 1'b1))) begin
            input_V_keep_V_0_sel_wr <= ~input_V_keep_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        input_V_keep_V_0_state <= 2'd0;
    end else begin
        if ((((input_V_keep_V_0_state == 2'd2) & (input_V_keep_V_0_vld_in == 1'b0)) | ((input_V_keep_V_0_state == 2'd3) & (input_V_keep_V_0_vld_in == 1'b0) & (input_V_keep_V_0_ack_out == 1'b1)))) begin
            input_V_keep_V_0_state <= 2'd2;
        end else if ((((input_V_keep_V_0_state == 2'd1) & (input_V_keep_V_0_ack_out == 1'b0)) | ((input_V_keep_V_0_state == 2'd3) & (input_V_keep_V_0_ack_out == 1'b0) & (input_V_keep_V_0_vld_in == 1'b1)))) begin
            input_V_keep_V_0_state <= 2'd1;
        end else if (((~((input_V_keep_V_0_vld_in == 1'b0) & (input_V_keep_V_0_ack_out == 1'b1)) & ~((input_V_keep_V_0_ack_out == 1'b0) & (input_V_keep_V_0_vld_in == 1'b1)) & (input_V_keep_V_0_state == 2'd3)) | ((input_V_keep_V_0_state == 2'd1) & (input_V_keep_V_0_ack_out == 1'b1)) | ((input_V_keep_V_0_state == 2'd2) & (input_V_keep_V_0_vld_in == 1'b1)))) begin
            input_V_keep_V_0_state <= 2'd3;
        end else begin
            input_V_keep_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        input_V_last_V_0_sel_rd <= 1'b0;
    end else begin
        if (((input_V_last_V_0_ack_out == 1'b1) & (input_V_last_V_0_vld_out == 1'b1))) begin
            input_V_last_V_0_sel_rd <= ~input_V_last_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        input_V_last_V_0_sel_wr <= 1'b0;
    end else begin
        if (((input_V_last_V_0_ack_in == 1'b1) & (input_V_last_V_0_vld_in == 1'b1))) begin
            input_V_last_V_0_sel_wr <= ~input_V_last_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        input_V_last_V_0_state <= 2'd0;
    end else begin
        if ((((input_V_last_V_0_state == 2'd2) & (input_V_last_V_0_vld_in == 1'b0)) | ((input_V_last_V_0_state == 2'd3) & (input_V_last_V_0_vld_in == 1'b0) & (input_V_last_V_0_ack_out == 1'b1)))) begin
            input_V_last_V_0_state <= 2'd2;
        end else if ((((input_V_last_V_0_state == 2'd1) & (input_V_last_V_0_ack_out == 1'b0)) | ((input_V_last_V_0_state == 2'd3) & (input_V_last_V_0_ack_out == 1'b0) & (input_V_last_V_0_vld_in == 1'b1)))) begin
            input_V_last_V_0_state <= 2'd1;
        end else if (((~((input_V_last_V_0_vld_in == 1'b0) & (input_V_last_V_0_ack_out == 1'b1)) & ~((input_V_last_V_0_ack_out == 1'b0) & (input_V_last_V_0_vld_in == 1'b1)) & (input_V_last_V_0_state == 2'd3)) | ((input_V_last_V_0_state == 2'd1) & (input_V_last_V_0_ack_out == 1'b1)) | ((input_V_last_V_0_state == 2'd2) & (input_V_last_V_0_vld_in == 1'b1)))) begin
            input_V_last_V_0_state <= 2'd3;
        end else begin
            input_V_last_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        input_V_user_V_0_state <= 2'd0;
    end else begin
        if ((((input_V_user_V_0_state == 2'd2) & (input_V_user_V_0_vld_in == 1'b0)) | ((input_V_user_V_0_state == 2'd3) & (input_V_user_V_0_vld_in == 1'b0) & (input_V_user_V_0_ack_out == 1'b1)))) begin
            input_V_user_V_0_state <= 2'd2;
        end else if ((((input_V_user_V_0_state == 2'd1) & (input_V_user_V_0_ack_out == 1'b0)) | ((input_V_user_V_0_state == 2'd3) & (input_V_user_V_0_ack_out == 1'b0) & (input_V_user_V_0_vld_in == 1'b1)))) begin
            input_V_user_V_0_state <= 2'd1;
        end else if (((~((input_V_user_V_0_vld_in == 1'b0) & (input_V_user_V_0_ack_out == 1'b1)) & ~((input_V_user_V_0_ack_out == 1'b0) & (input_V_user_V_0_vld_in == 1'b1)) & (input_V_user_V_0_state == 2'd3)) | ((input_V_user_V_0_state == 2'd1) & (input_V_user_V_0_ack_out == 1'b1)) | ((input_V_user_V_0_state == 2'd2) & (input_V_user_V_0_vld_in == 1'b1)))) begin
            input_V_user_V_0_state <= 2'd3;
        end else begin
            input_V_user_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        output_V_data_V_1_sel_rd <= 1'b0;
    end else begin
        if (((output_V_data_V_1_ack_out == 1'b1) & (output_V_data_V_1_vld_out == 1'b1))) begin
            output_V_data_V_1_sel_rd <= ~output_V_data_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        output_V_data_V_1_sel_wr <= 1'b0;
    end else begin
        if (((output_V_data_V_1_ack_in == 1'b1) & (output_V_data_V_1_vld_in == 1'b1))) begin
            output_V_data_V_1_sel_wr <= ~output_V_data_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        output_V_data_V_1_state <= 2'd0;
    end else begin
        if ((((output_V_data_V_1_state == 2'd2) & (output_V_data_V_1_vld_in == 1'b0)) | ((output_V_data_V_1_state == 2'd3) & (output_V_data_V_1_vld_in == 1'b0) & (output_V_data_V_1_ack_out == 1'b1)))) begin
            output_V_data_V_1_state <= 2'd2;
        end else if ((((output_V_data_V_1_state == 2'd1) & (n2G_output_TREADY == 1'b0)) | ((output_V_data_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0) & (output_V_data_V_1_vld_in == 1'b1)))) begin
            output_V_data_V_1_state <= 2'd1;
        end else if (((~((output_V_data_V_1_vld_in == 1'b0) & (output_V_data_V_1_ack_out == 1'b1)) & ~((n2G_output_TREADY == 1'b0) & (output_V_data_V_1_vld_in == 1'b1)) & (output_V_data_V_1_state == 2'd3)) | ((output_V_data_V_1_state == 2'd1) & (output_V_data_V_1_ack_out == 1'b1)) | ((output_V_data_V_1_state == 2'd2) & (output_V_data_V_1_vld_in == 1'b1)))) begin
            output_V_data_V_1_state <= 2'd3;
        end else begin
            output_V_data_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        output_V_dest_V_1_sel_rd <= 1'b0;
    end else begin
        if (((output_V_dest_V_1_ack_out == 1'b1) & (output_V_dest_V_1_vld_out == 1'b1))) begin
            output_V_dest_V_1_sel_rd <= ~output_V_dest_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        output_V_dest_V_1_sel_wr <= 1'b0;
    end else begin
        if (((output_V_dest_V_1_ack_in == 1'b1) & (output_V_dest_V_1_vld_in == 1'b1))) begin
            output_V_dest_V_1_sel_wr <= ~output_V_dest_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        output_V_dest_V_1_state <= 2'd0;
    end else begin
        if ((((output_V_dest_V_1_state == 2'd2) & (output_V_dest_V_1_vld_in == 1'b0)) | ((output_V_dest_V_1_state == 2'd3) & (output_V_dest_V_1_vld_in == 1'b0) & (output_V_dest_V_1_ack_out == 1'b1)))) begin
            output_V_dest_V_1_state <= 2'd2;
        end else if ((((output_V_dest_V_1_state == 2'd1) & (n2G_output_TREADY == 1'b0)) | ((output_V_dest_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0) & (output_V_dest_V_1_vld_in == 1'b1)))) begin
            output_V_dest_V_1_state <= 2'd1;
        end else if (((~((output_V_dest_V_1_vld_in == 1'b0) & (output_V_dest_V_1_ack_out == 1'b1)) & ~((n2G_output_TREADY == 1'b0) & (output_V_dest_V_1_vld_in == 1'b1)) & (output_V_dest_V_1_state == 2'd3)) | ((output_V_dest_V_1_state == 2'd1) & (output_V_dest_V_1_ack_out == 1'b1)) | ((output_V_dest_V_1_state == 2'd2) & (output_V_dest_V_1_vld_in == 1'b1)))) begin
            output_V_dest_V_1_state <= 2'd3;
        end else begin
            output_V_dest_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        output_V_id_V_1_sel_rd <= 1'b0;
    end else begin
        if (((output_V_id_V_1_ack_out == 1'b1) & (output_V_id_V_1_vld_out == 1'b1))) begin
            output_V_id_V_1_sel_rd <= ~output_V_id_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        output_V_id_V_1_sel_wr <= 1'b0;
    end else begin
        if (((output_V_id_V_1_ack_in == 1'b1) & (output_V_id_V_1_vld_in == 1'b1))) begin
            output_V_id_V_1_sel_wr <= ~output_V_id_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        output_V_id_V_1_state <= 2'd0;
    end else begin
        if ((((output_V_id_V_1_state == 2'd2) & (output_V_id_V_1_vld_in == 1'b0)) | ((output_V_id_V_1_state == 2'd3) & (output_V_id_V_1_vld_in == 1'b0) & (output_V_id_V_1_ack_out == 1'b1)))) begin
            output_V_id_V_1_state <= 2'd2;
        end else if ((((output_V_id_V_1_state == 2'd1) & (n2G_output_TREADY == 1'b0)) | ((output_V_id_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0) & (output_V_id_V_1_vld_in == 1'b1)))) begin
            output_V_id_V_1_state <= 2'd1;
        end else if (((~((output_V_id_V_1_vld_in == 1'b0) & (output_V_id_V_1_ack_out == 1'b1)) & ~((n2G_output_TREADY == 1'b0) & (output_V_id_V_1_vld_in == 1'b1)) & (output_V_id_V_1_state == 2'd3)) | ((output_V_id_V_1_state == 2'd1) & (output_V_id_V_1_ack_out == 1'b1)) | ((output_V_id_V_1_state == 2'd2) & (output_V_id_V_1_vld_in == 1'b1)))) begin
            output_V_id_V_1_state <= 2'd3;
        end else begin
            output_V_id_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        output_V_keep_V_1_sel_rd <= 1'b0;
    end else begin
        if (((output_V_keep_V_1_ack_out == 1'b1) & (output_V_keep_V_1_vld_out == 1'b1))) begin
            output_V_keep_V_1_sel_rd <= ~output_V_keep_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        output_V_keep_V_1_sel_wr <= 1'b0;
    end else begin
        if (((output_V_keep_V_1_ack_in == 1'b1) & (output_V_keep_V_1_vld_in == 1'b1))) begin
            output_V_keep_V_1_sel_wr <= ~output_V_keep_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        output_V_keep_V_1_state <= 2'd0;
    end else begin
        if ((((output_V_keep_V_1_state == 2'd2) & (output_V_keep_V_1_vld_in == 1'b0)) | ((output_V_keep_V_1_state == 2'd3) & (output_V_keep_V_1_vld_in == 1'b0) & (output_V_keep_V_1_ack_out == 1'b1)))) begin
            output_V_keep_V_1_state <= 2'd2;
        end else if ((((output_V_keep_V_1_state == 2'd1) & (n2G_output_TREADY == 1'b0)) | ((output_V_keep_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0) & (output_V_keep_V_1_vld_in == 1'b1)))) begin
            output_V_keep_V_1_state <= 2'd1;
        end else if (((~((output_V_keep_V_1_vld_in == 1'b0) & (output_V_keep_V_1_ack_out == 1'b1)) & ~((n2G_output_TREADY == 1'b0) & (output_V_keep_V_1_vld_in == 1'b1)) & (output_V_keep_V_1_state == 2'd3)) | ((output_V_keep_V_1_state == 2'd1) & (output_V_keep_V_1_ack_out == 1'b1)) | ((output_V_keep_V_1_state == 2'd2) & (output_V_keep_V_1_vld_in == 1'b1)))) begin
            output_V_keep_V_1_state <= 2'd3;
        end else begin
            output_V_keep_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        output_V_last_V_1_sel_rd <= 1'b0;
    end else begin
        if (((output_V_last_V_1_ack_out == 1'b1) & (output_V_last_V_1_vld_out == 1'b1))) begin
            output_V_last_V_1_sel_rd <= ~output_V_last_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        output_V_last_V_1_sel_wr <= 1'b0;
    end else begin
        if (((output_V_last_V_1_ack_in == 1'b1) & (output_V_last_V_1_vld_in == 1'b1))) begin
            output_V_last_V_1_sel_wr <= ~output_V_last_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        output_V_last_V_1_state <= 2'd0;
    end else begin
        if ((((output_V_last_V_1_state == 2'd2) & (output_V_last_V_1_vld_in == 1'b0)) | ((output_V_last_V_1_state == 2'd3) & (output_V_last_V_1_vld_in == 1'b0) & (output_V_last_V_1_ack_out == 1'b1)))) begin
            output_V_last_V_1_state <= 2'd2;
        end else if ((((output_V_last_V_1_state == 2'd1) & (n2G_output_TREADY == 1'b0)) | ((output_V_last_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0) & (output_V_last_V_1_vld_in == 1'b1)))) begin
            output_V_last_V_1_state <= 2'd1;
        end else if (((~((output_V_last_V_1_vld_in == 1'b0) & (output_V_last_V_1_ack_out == 1'b1)) & ~((n2G_output_TREADY == 1'b0) & (output_V_last_V_1_vld_in == 1'b1)) & (output_V_last_V_1_state == 2'd3)) | ((output_V_last_V_1_state == 2'd1) & (output_V_last_V_1_ack_out == 1'b1)) | ((output_V_last_V_1_state == 2'd2) & (output_V_last_V_1_vld_in == 1'b1)))) begin
            output_V_last_V_1_state <= 2'd3;
        end else begin
            output_V_last_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        output_V_user_V_1_sel_rd <= 1'b0;
    end else begin
        if (((output_V_user_V_1_ack_out == 1'b1) & (output_V_user_V_1_vld_out == 1'b1))) begin
            output_V_user_V_1_sel_rd <= ~output_V_user_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        output_V_user_V_1_sel_wr <= 1'b0;
    end else begin
        if (((output_V_user_V_1_ack_in == 1'b1) & (output_V_user_V_1_vld_in == 1'b1))) begin
            output_V_user_V_1_sel_wr <= ~output_V_user_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        output_V_user_V_1_state <= 2'd0;
    end else begin
        if ((((output_V_user_V_1_state == 2'd2) & (output_V_user_V_1_vld_in == 1'b0)) | ((output_V_user_V_1_state == 2'd3) & (output_V_user_V_1_vld_in == 1'b0) & (output_V_user_V_1_ack_out == 1'b1)))) begin
            output_V_user_V_1_state <= 2'd2;
        end else if ((((output_V_user_V_1_state == 2'd1) & (n2G_output_TREADY == 1'b0)) | ((output_V_user_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0) & (output_V_user_V_1_vld_in == 1'b1)))) begin
            output_V_user_V_1_state <= 2'd1;
        end else if (((~((output_V_user_V_1_vld_in == 1'b0) & (output_V_user_V_1_ack_out == 1'b1)) & ~((n2G_output_TREADY == 1'b0) & (output_V_user_V_1_vld_in == 1'b1)) & (output_V_user_V_1_state == 2'd3)) | ((output_V_user_V_1_state == 2'd1) & (output_V_user_V_1_ack_out == 1'b1)) | ((output_V_user_V_1_state == 2'd2) & (output_V_user_V_1_vld_in == 1'b1)))) begin
            output_V_user_V_1_state <= 2'd3;
        end else begin
            output_V_user_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln69_fu_137_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_op_assign_reg_98 <= i_fu_142_p2;
    end else if ((~((ap_start == 1'b0) | (input_V_data_V_0_vld_out == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_op_assign_reg_98 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (input_V_data_V_0_vld_out == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        dest_V_reg_161 <= {{input_V_data_V_0_data_out[31:24]}};
        id_V_reg_156 <= {{input_V_data_V_0_data_out[23:16]}};
        size_V_reg_166 <= size_V_fu_133_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln69_reg_172 <= icmp_ln69_fu_137_p2;
        icmp_ln69_reg_172_pp0_iter1_reg <= icmp_ln69_reg_172;
    end
end

always @ (posedge ap_clk) begin
    if ((input_V_data_V_0_load_A == 1'b1)) begin
        input_V_data_V_0_payload_A <= n2G_input_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((input_V_data_V_0_load_B == 1'b1)) begin
        input_V_data_V_0_payload_B <= n2G_input_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((input_V_keep_V_0_load_A == 1'b1)) begin
        input_V_keep_V_0_payload_A <= n2G_input_TKEEP;
    end
end

always @ (posedge ap_clk) begin
    if ((input_V_keep_V_0_load_B == 1'b1)) begin
        input_V_keep_V_0_payload_B <= n2G_input_TKEEP;
    end
end

always @ (posedge ap_clk) begin
    if ((input_V_last_V_0_load_A == 1'b1)) begin
        input_V_last_V_0_payload_A <= n2G_input_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if ((input_V_last_V_0_load_B == 1'b1)) begin
        input_V_last_V_0_payload_B <= n2G_input_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if ((output_V_data_V_1_load_A == 1'b1)) begin
        output_V_data_V_1_payload_A <= tmp_data_V_reg_181;
    end
end

always @ (posedge ap_clk) begin
    if ((output_V_data_V_1_load_B == 1'b1)) begin
        output_V_data_V_1_payload_B <= tmp_data_V_reg_181;
    end
end

always @ (posedge ap_clk) begin
    if ((output_V_dest_V_1_load_A == 1'b1)) begin
        output_V_dest_V_1_payload_A <= dest_V_reg_161;
    end
end

always @ (posedge ap_clk) begin
    if ((output_V_dest_V_1_load_B == 1'b1)) begin
        output_V_dest_V_1_payload_B <= dest_V_reg_161;
    end
end

always @ (posedge ap_clk) begin
    if ((output_V_id_V_1_load_A == 1'b1)) begin
        output_V_id_V_1_payload_A <= id_V_reg_156;
    end
end

always @ (posedge ap_clk) begin
    if ((output_V_id_V_1_load_B == 1'b1)) begin
        output_V_id_V_1_payload_B <= id_V_reg_156;
    end
end

always @ (posedge ap_clk) begin
    if ((output_V_keep_V_1_load_A == 1'b1)) begin
        output_V_keep_V_1_payload_A <= tmp_keep_V_reg_186;
    end
end

always @ (posedge ap_clk) begin
    if ((output_V_keep_V_1_load_B == 1'b1)) begin
        output_V_keep_V_1_payload_B <= tmp_keep_V_reg_186;
    end
end

always @ (posedge ap_clk) begin
    if ((output_V_last_V_1_load_A == 1'b1)) begin
        output_V_last_V_1_payload_A <= tmp_last_V_reg_191;
    end
end

always @ (posedge ap_clk) begin
    if ((output_V_last_V_1_load_B == 1'b1)) begin
        output_V_last_V_1_payload_B <= tmp_last_V_reg_191;
    end
end

always @ (posedge ap_clk) begin
    if ((output_V_user_V_1_load_A == 1'b1)) begin
        output_V_user_V_1_payload_A <= size_V_reg_166;
    end
end

always @ (posedge ap_clk) begin
    if ((output_V_user_V_1_load_B == 1'b1)) begin
        output_V_user_V_1_payload_B <= size_V_reg_166;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln69_fu_137_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_data_V_reg_181 <= input_V_data_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln69_fu_137_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_keep_V_reg_186 <= input_V_keep_V_0_data_out;
        tmp_last_V_reg_191 <= input_V_last_V_0_data_out;
    end
end

always @ (*) begin
    if ((icmp_ln69_fu_137_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((~((output_V_keep_V_1_state == 2'd1) | (output_V_user_V_1_state == 2'd1) | (output_V_id_V_1_state == 2'd1) | (output_V_last_V_1_state == 2'd1) | (output_V_dest_V_1_state == 2'd1) | (output_V_data_V_1_state == 2'd1) | ((output_V_keep_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0)) | ((output_V_user_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0)) | ((output_V_id_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0)) | ((output_V_last_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0)) | ((output_V_dest_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0)) | ((output_V_data_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0))) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((output_V_keep_V_1_state == 2'd1) | (output_V_user_V_1_state == 2'd1) | (output_V_id_V_1_state == 2'd1) | (output_V_last_V_1_state == 2'd1) | (output_V_dest_V_1_state == 2'd1) | (output_V_data_V_1_state == 2'd1) | ((output_V_keep_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0)) | ((output_V_user_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0)) | ((output_V_id_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0)) | ((output_V_last_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0)) | ((output_V_dest_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0)) | ((output_V_data_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0))) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln69_fu_137_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~((ap_start == 1'b0) | (input_V_data_V_0_vld_out == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        input_V_data_V_0_ack_out = 1'b1;
    end else begin
        input_V_data_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((input_V_data_V_0_sel == 1'b1)) begin
        input_V_data_V_0_data_out = input_V_data_V_0_payload_B;
    end else begin
        input_V_data_V_0_data_out = input_V_data_V_0_payload_A;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln69_fu_137_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~((ap_start == 1'b0) | (input_V_data_V_0_vld_out == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        input_V_keep_V_0_ack_out = 1'b1;
    end else begin
        input_V_keep_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((input_V_keep_V_0_sel == 1'b1)) begin
        input_V_keep_V_0_data_out = input_V_keep_V_0_payload_B;
    end else begin
        input_V_keep_V_0_data_out = input_V_keep_V_0_payload_A;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln69_fu_137_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~((ap_start == 1'b0) | (input_V_data_V_0_vld_out == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        input_V_last_V_0_ack_out = 1'b1;
    end else begin
        input_V_last_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((input_V_last_V_0_sel == 1'b1)) begin
        input_V_last_V_0_data_out = input_V_last_V_0_payload_B;
    end else begin
        input_V_last_V_0_data_out = input_V_last_V_0_payload_A;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln69_fu_137_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~((ap_start == 1'b0) | (input_V_data_V_0_vld_out == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        input_V_user_V_0_ack_out = 1'b1;
    end else begin
        input_V_user_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (icmp_ln69_fu_137_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        n2G_input_TDATA_blk_n = input_V_data_V_0_state[1'd0];
    end else begin
        n2G_input_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (icmp_ln69_reg_172_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (icmp_ln69_reg_172 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        n2G_output_TDATA_blk_n = output_V_data_V_1_state[1'd1];
    end else begin
        n2G_output_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((output_V_data_V_1_sel == 1'b1)) begin
        output_V_data_V_1_data_out = output_V_data_V_1_payload_B;
    end else begin
        output_V_data_V_1_data_out = output_V_data_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln69_reg_172 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        output_V_data_V_1_vld_in = 1'b1;
    end else begin
        output_V_data_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((output_V_dest_V_1_sel == 1'b1)) begin
        output_V_dest_V_1_data_out = output_V_dest_V_1_payload_B;
    end else begin
        output_V_dest_V_1_data_out = output_V_dest_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln69_reg_172 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        output_V_dest_V_1_vld_in = 1'b1;
    end else begin
        output_V_dest_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((output_V_id_V_1_sel == 1'b1)) begin
        output_V_id_V_1_data_out = output_V_id_V_1_payload_B;
    end else begin
        output_V_id_V_1_data_out = output_V_id_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln69_reg_172 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        output_V_id_V_1_vld_in = 1'b1;
    end else begin
        output_V_id_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((output_V_keep_V_1_sel == 1'b1)) begin
        output_V_keep_V_1_data_out = output_V_keep_V_1_payload_B;
    end else begin
        output_V_keep_V_1_data_out = output_V_keep_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln69_reg_172 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        output_V_keep_V_1_vld_in = 1'b1;
    end else begin
        output_V_keep_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((output_V_last_V_1_sel == 1'b1)) begin
        output_V_last_V_1_data_out = output_V_last_V_1_payload_B;
    end else begin
        output_V_last_V_1_data_out = output_V_last_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln69_reg_172 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        output_V_last_V_1_vld_in = 1'b1;
    end else begin
        output_V_last_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((output_V_user_V_1_sel == 1'b1)) begin
        output_V_user_V_1_data_out = output_V_user_V_1_payload_B;
    end else begin
        output_V_user_V_1_data_out = output_V_user_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln69_reg_172 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        output_V_user_V_1_vld_in = 1'b1;
    end else begin
        output_V_user_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (input_V_data_V_0_vld_out == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (icmp_ln69_fu_137_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (icmp_ln69_fu_137_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            if ((~((output_V_keep_V_1_state == 2'd1) | (output_V_user_V_1_state == 2'd1) | (output_V_id_V_1_state == 2'd1) | (output_V_last_V_1_state == 2'd1) | (output_V_dest_V_1_state == 2'd1) | (output_V_data_V_1_state == 2'd1) | ((output_V_keep_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0)) | ((output_V_user_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0)) | ((output_V_id_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0)) | ((output_V_last_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0)) | ((output_V_dest_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0)) | ((output_V_data_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0))) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((icmp_ln69_fu_137_p2 == 1'd0) & (input_V_data_V_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((1'b1 == ap_block_state4_io) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b1 == ap_block_state3_io) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((icmp_ln69_fu_137_p2 == 1'd0) & (input_V_data_V_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((1'b1 == ap_block_state4_io) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b1 == ap_block_state3_io) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((icmp_ln69_fu_137_p2 == 1'd0) & (input_V_data_V_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (input_V_data_V_0_vld_out == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = ((icmp_ln69_fu_137_p2 == 1'd0) & (input_V_data_V_0_vld_out == 1'b0));
end

always @ (*) begin
    ap_block_state3_io = ((icmp_ln69_reg_172 == 1'd0) & (output_V_data_V_1_ack_in == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_io = ((icmp_ln69_reg_172_pp0_iter1_reg == 1'd0) & (output_V_data_V_1_ack_in == 1'b0));
end

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5 = ((output_V_keep_V_1_state == 2'd1) | (output_V_user_V_1_state == 2'd1) | (output_V_id_V_1_state == 2'd1) | (output_V_last_V_1_state == 2'd1) | (output_V_dest_V_1_state == 2'd1) | (output_V_data_V_1_state == 2'd1) | ((output_V_keep_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0)) | ((output_V_user_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0)) | ((output_V_id_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0)) | ((output_V_last_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0)) | ((output_V_dest_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0)) | ((output_V_data_V_1_state == 2'd3) & (n2G_output_TREADY == 1'b0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign i_fu_142_p2 = (i_op_assign_reg_98 + 16'd1);

assign icmp_ln69_fu_137_p2 = ((i_op_assign_reg_98 == size_V_reg_166) ? 1'b1 : 1'b0);

assign input_V_data_V_0_ack_in = input_V_data_V_0_state[1'd1];

assign input_V_data_V_0_load_A = (input_V_data_V_0_state_cmp_full & ~input_V_data_V_0_sel_wr);

assign input_V_data_V_0_load_B = (input_V_data_V_0_state_cmp_full & input_V_data_V_0_sel_wr);

assign input_V_data_V_0_sel = input_V_data_V_0_sel_rd;

assign input_V_data_V_0_state_cmp_full = ((input_V_data_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign input_V_data_V_0_vld_in = n2G_input_TVALID;

assign input_V_data_V_0_vld_out = input_V_data_V_0_state[1'd0];

assign input_V_keep_V_0_ack_in = input_V_keep_V_0_state[1'd1];

assign input_V_keep_V_0_load_A = (input_V_keep_V_0_state_cmp_full & ~input_V_keep_V_0_sel_wr);

assign input_V_keep_V_0_load_B = (input_V_keep_V_0_state_cmp_full & input_V_keep_V_0_sel_wr);

assign input_V_keep_V_0_sel = input_V_keep_V_0_sel_rd;

assign input_V_keep_V_0_state_cmp_full = ((input_V_keep_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign input_V_keep_V_0_vld_in = n2G_input_TVALID;

assign input_V_keep_V_0_vld_out = input_V_keep_V_0_state[1'd0];

assign input_V_last_V_0_ack_in = input_V_last_V_0_state[1'd1];

assign input_V_last_V_0_load_A = (input_V_last_V_0_state_cmp_full & ~input_V_last_V_0_sel_wr);

assign input_V_last_V_0_load_B = (input_V_last_V_0_state_cmp_full & input_V_last_V_0_sel_wr);

assign input_V_last_V_0_sel = input_V_last_V_0_sel_rd;

assign input_V_last_V_0_state_cmp_full = ((input_V_last_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign input_V_last_V_0_vld_in = n2G_input_TVALID;

assign input_V_last_V_0_vld_out = input_V_last_V_0_state[1'd0];

assign input_V_user_V_0_vld_in = n2G_input_TVALID;

assign n2G_input_TREADY = input_V_user_V_0_state[1'd1];

assign n2G_output_TDATA = output_V_data_V_1_data_out;

assign n2G_output_TDEST = output_V_dest_V_1_data_out;

assign n2G_output_TID = output_V_id_V_1_data_out;

assign n2G_output_TKEEP = output_V_keep_V_1_data_out;

assign n2G_output_TLAST = output_V_last_V_1_data_out;

assign n2G_output_TUSER = output_V_user_V_1_data_out;

assign n2G_output_TVALID = output_V_keep_V_1_state[1'd0];

assign output_V_data_V_1_ack_in = output_V_data_V_1_state[1'd1];

assign output_V_data_V_1_ack_out = n2G_output_TREADY;

assign output_V_data_V_1_load_A = (output_V_data_V_1_state_cmp_full & ~output_V_data_V_1_sel_wr);

assign output_V_data_V_1_load_B = (output_V_data_V_1_state_cmp_full & output_V_data_V_1_sel_wr);

assign output_V_data_V_1_sel = output_V_data_V_1_sel_rd;

assign output_V_data_V_1_state_cmp_full = ((output_V_data_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign output_V_data_V_1_vld_out = output_V_data_V_1_state[1'd0];

assign output_V_dest_V_1_ack_in = output_V_dest_V_1_state[1'd1];

assign output_V_dest_V_1_ack_out = n2G_output_TREADY;

assign output_V_dest_V_1_load_A = (output_V_dest_V_1_state_cmp_full & ~output_V_dest_V_1_sel_wr);

assign output_V_dest_V_1_load_B = (output_V_dest_V_1_state_cmp_full & output_V_dest_V_1_sel_wr);

assign output_V_dest_V_1_sel = output_V_dest_V_1_sel_rd;

assign output_V_dest_V_1_state_cmp_full = ((output_V_dest_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign output_V_dest_V_1_vld_out = output_V_dest_V_1_state[1'd0];

assign output_V_id_V_1_ack_in = output_V_id_V_1_state[1'd1];

assign output_V_id_V_1_ack_out = n2G_output_TREADY;

assign output_V_id_V_1_load_A = (output_V_id_V_1_state_cmp_full & ~output_V_id_V_1_sel_wr);

assign output_V_id_V_1_load_B = (output_V_id_V_1_state_cmp_full & output_V_id_V_1_sel_wr);

assign output_V_id_V_1_sel = output_V_id_V_1_sel_rd;

assign output_V_id_V_1_state_cmp_full = ((output_V_id_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign output_V_id_V_1_vld_out = output_V_id_V_1_state[1'd0];

assign output_V_keep_V_1_ack_in = output_V_keep_V_1_state[1'd1];

assign output_V_keep_V_1_ack_out = n2G_output_TREADY;

assign output_V_keep_V_1_load_A = (output_V_keep_V_1_state_cmp_full & ~output_V_keep_V_1_sel_wr);

assign output_V_keep_V_1_load_B = (output_V_keep_V_1_state_cmp_full & output_V_keep_V_1_sel_wr);

assign output_V_keep_V_1_sel = output_V_keep_V_1_sel_rd;

assign output_V_keep_V_1_state_cmp_full = ((output_V_keep_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign output_V_keep_V_1_vld_out = output_V_keep_V_1_state[1'd0];

assign output_V_last_V_1_ack_in = output_V_last_V_1_state[1'd1];

assign output_V_last_V_1_ack_out = n2G_output_TREADY;

assign output_V_last_V_1_load_A = (output_V_last_V_1_state_cmp_full & ~output_V_last_V_1_sel_wr);

assign output_V_last_V_1_load_B = (output_V_last_V_1_state_cmp_full & output_V_last_V_1_sel_wr);

assign output_V_last_V_1_sel = output_V_last_V_1_sel_rd;

assign output_V_last_V_1_state_cmp_full = ((output_V_last_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign output_V_last_V_1_vld_out = output_V_last_V_1_state[1'd0];

assign output_V_user_V_1_ack_in = output_V_user_V_1_state[1'd1];

assign output_V_user_V_1_ack_out = n2G_output_TREADY;

assign output_V_user_V_1_load_A = (output_V_user_V_1_state_cmp_full & ~output_V_user_V_1_sel_wr);

assign output_V_user_V_1_load_B = (output_V_user_V_1_state_cmp_full & output_V_user_V_1_sel_wr);

assign output_V_user_V_1_sel = output_V_user_V_1_sel_rd;

assign output_V_user_V_1_state_cmp_full = ((output_V_user_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign output_V_user_V_1_vld_out = output_V_user_V_1_state[1'd0];

assign size_V_fu_133_p1 = input_V_data_V_0_data_out[15:0];

endmodule //n2G
