-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity rxPath is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    lbRxDataIn_TVALID : IN STD_LOGIC;
    txGalapagosBridge_TREADY : IN STD_LOGIC;
    lbRxDataIn_TDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    lbRxDataIn_TREADY : OUT STD_LOGIC;
    lbRxDataIn_TKEEP : IN STD_LOGIC_VECTOR (15 downto 0);
    lbRxDataIn_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    txGalapagosBridge_TDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    txGalapagosBridge_TVALID : OUT STD_LOGIC;
    txGalapagosBridge_TKEEP : OUT STD_LOGIC_VECTOR (15 downto 0);
    txGalapagosBridge_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    id_V : OUT STD_LOGIC_VECTOR (7 downto 0);
    id_V_ap_vld : OUT STD_LOGIC;
    dest_V : OUT STD_LOGIC_VECTOR (7 downto 0);
    dest_V_ap_vld : OUT STD_LOGIC;
    size_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    size_V_ap_vld : OUT STD_LOGIC );
end;


architecture behav of rxPath is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal tmp_nbreadreq_fu_52_p5 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal txGalapagosBridge_V_data_V_1_ack_in : STD_LOGIC;
    signal tmp_reg_147 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_io : BOOLEAN;
    signal txGalapagosBridge_V_data_V_1_ack_out : STD_LOGIC;
    signal txGalapagosBridge_V_data_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal txGalapagosBridge_V_keep_V_1_ack_out : STD_LOGIC;
    signal txGalapagosBridge_V_keep_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal txGalapagosBridge_V_last_V_1_ack_out : STD_LOGIC;
    signal txGalapagosBridge_V_last_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal tmp_reg_147_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal txGalapagosBridge_V_data_V_1_data_out : STD_LOGIC_VECTOR (511 downto 0);
    signal txGalapagosBridge_V_data_V_1_vld_in : STD_LOGIC;
    signal txGalapagosBridge_V_data_V_1_vld_out : STD_LOGIC;
    signal txGalapagosBridge_V_data_V_1_payload_A : STD_LOGIC_VECTOR (511 downto 0);
    signal txGalapagosBridge_V_data_V_1_payload_B : STD_LOGIC_VECTOR (511 downto 0);
    signal txGalapagosBridge_V_data_V_1_sel_rd : STD_LOGIC := '0';
    signal txGalapagosBridge_V_data_V_1_sel_wr : STD_LOGIC := '0';
    signal txGalapagosBridge_V_data_V_1_sel : STD_LOGIC;
    signal txGalapagosBridge_V_data_V_1_load_A : STD_LOGIC;
    signal txGalapagosBridge_V_data_V_1_load_B : STD_LOGIC;
    signal txGalapagosBridge_V_data_V_1_state_cmp_full : STD_LOGIC;
    signal txGalapagosBridge_V_keep_V_1_data_out : STD_LOGIC_VECTOR (15 downto 0);
    signal txGalapagosBridge_V_keep_V_1_vld_in : STD_LOGIC;
    signal txGalapagosBridge_V_keep_V_1_vld_out : STD_LOGIC;
    signal txGalapagosBridge_V_keep_V_1_ack_in : STD_LOGIC;
    signal txGalapagosBridge_V_keep_V_1_payload_A : STD_LOGIC_VECTOR (15 downto 0);
    signal txGalapagosBridge_V_keep_V_1_payload_B : STD_LOGIC_VECTOR (15 downto 0);
    signal txGalapagosBridge_V_keep_V_1_sel_rd : STD_LOGIC := '0';
    signal txGalapagosBridge_V_keep_V_1_sel_wr : STD_LOGIC := '0';
    signal txGalapagosBridge_V_keep_V_1_sel : STD_LOGIC;
    signal txGalapagosBridge_V_keep_V_1_load_A : STD_LOGIC;
    signal txGalapagosBridge_V_keep_V_1_load_B : STD_LOGIC;
    signal txGalapagosBridge_V_keep_V_1_state_cmp_full : STD_LOGIC;
    signal txGalapagosBridge_V_last_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal txGalapagosBridge_V_last_V_1_vld_in : STD_LOGIC;
    signal txGalapagosBridge_V_last_V_1_vld_out : STD_LOGIC;
    signal txGalapagosBridge_V_last_V_1_ack_in : STD_LOGIC;
    signal txGalapagosBridge_V_last_V_1_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal txGalapagosBridge_V_last_V_1_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal txGalapagosBridge_V_last_V_1_sel_rd : STD_LOGIC := '0';
    signal txGalapagosBridge_V_last_V_1_sel_wr : STD_LOGIC := '0';
    signal txGalapagosBridge_V_last_V_1_sel : STD_LOGIC;
    signal txGalapagosBridge_V_last_V_1_load_A : STD_LOGIC;
    signal txGalapagosBridge_V_last_V_1_load_B : STD_LOGIC;
    signal txGalapagosBridge_V_last_V_1_state_cmp_full : STD_LOGIC;
    signal lbRxDataIn_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal txGalapagosBridge_TDATA_blk_n : STD_LOGIC;
    signal tmp_data_V_reg_151 : STD_LOGIC_VECTOR (511 downto 0);
    signal tmp_keep_V_reg_156 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_last_V_reg_161 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal id_V_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal dest_V_preg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal trunc_ln647_fu_142_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal size_V_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to1 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    dest_V_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                dest_V_preg <= ap_const_lv8_0;
            else
                if (((tmp_nbreadreq_fu_52_p5 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    dest_V_preg <= lbRxDataIn_TDATA(31 downto 24);
                end if; 
            end if;
        end if;
    end process;


    id_V_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                id_V_preg <= ap_const_lv8_0;
            else
                if (((tmp_nbreadreq_fu_52_p5 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    id_V_preg <= lbRxDataIn_TDATA(23 downto 16);
                end if; 
            end if;
        end if;
    end process;


    size_V_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                size_V_preg <= ap_const_lv16_0;
            else
                if (((tmp_nbreadreq_fu_52_p5 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    size_V_preg <= trunc_ln647_fu_142_p1;
                end if; 
            end if;
        end if;
    end process;


    txGalapagosBridge_V_data_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                txGalapagosBridge_V_data_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((txGalapagosBridge_V_data_V_1_ack_out = ap_const_logic_1) and (txGalapagosBridge_V_data_V_1_vld_out = ap_const_logic_1))) then 
                                        txGalapagosBridge_V_data_V_1_sel_rd <= not(txGalapagosBridge_V_data_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    txGalapagosBridge_V_data_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                txGalapagosBridge_V_data_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((txGalapagosBridge_V_data_V_1_ack_in = ap_const_logic_1) and (txGalapagosBridge_V_data_V_1_vld_in = ap_const_logic_1))) then 
                                        txGalapagosBridge_V_data_V_1_sel_wr <= not(txGalapagosBridge_V_data_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    txGalapagosBridge_V_data_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                txGalapagosBridge_V_data_V_1_state <= ap_const_lv2_0;
            else
                if ((((txGalapagosBridge_V_data_V_1_state = ap_const_lv2_3) and (txGalapagosBridge_V_data_V_1_vld_in = ap_const_logic_0) and (txGalapagosBridge_V_data_V_1_ack_out = ap_const_logic_1)) or ((txGalapagosBridge_V_data_V_1_state = ap_const_lv2_2) and (txGalapagosBridge_V_data_V_1_vld_in = ap_const_logic_0)))) then 
                    txGalapagosBridge_V_data_V_1_state <= ap_const_lv2_2;
                elsif ((((txGalapagosBridge_V_data_V_1_state = ap_const_lv2_1) and (txGalapagosBridge_TREADY = ap_const_logic_0)) or ((txGalapagosBridge_V_data_V_1_state = ap_const_lv2_3) and (txGalapagosBridge_TREADY = ap_const_logic_0) and (txGalapagosBridge_V_data_V_1_vld_in = ap_const_logic_1)))) then 
                    txGalapagosBridge_V_data_V_1_state <= ap_const_lv2_1;
                elsif ((((txGalapagosBridge_V_data_V_1_state = ap_const_lv2_1) and (txGalapagosBridge_V_data_V_1_ack_out = ap_const_logic_1)) or (not(((txGalapagosBridge_V_data_V_1_vld_in = ap_const_logic_0) and (txGalapagosBridge_V_data_V_1_ack_out = ap_const_logic_1))) and not(((txGalapagosBridge_TREADY = ap_const_logic_0) and (txGalapagosBridge_V_data_V_1_vld_in = ap_const_logic_1))) and (txGalapagosBridge_V_data_V_1_state = ap_const_lv2_3)) or ((txGalapagosBridge_V_data_V_1_state = ap_const_lv2_2) and (txGalapagosBridge_V_data_V_1_vld_in = ap_const_logic_1)))) then 
                    txGalapagosBridge_V_data_V_1_state <= ap_const_lv2_3;
                else 
                    txGalapagosBridge_V_data_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    txGalapagosBridge_V_keep_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                txGalapagosBridge_V_keep_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((txGalapagosBridge_V_keep_V_1_ack_out = ap_const_logic_1) and (txGalapagosBridge_V_keep_V_1_vld_out = ap_const_logic_1))) then 
                                        txGalapagosBridge_V_keep_V_1_sel_rd <= not(txGalapagosBridge_V_keep_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    txGalapagosBridge_V_keep_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                txGalapagosBridge_V_keep_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((txGalapagosBridge_V_keep_V_1_ack_in = ap_const_logic_1) and (txGalapagosBridge_V_keep_V_1_vld_in = ap_const_logic_1))) then 
                                        txGalapagosBridge_V_keep_V_1_sel_wr <= not(txGalapagosBridge_V_keep_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    txGalapagosBridge_V_keep_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                txGalapagosBridge_V_keep_V_1_state <= ap_const_lv2_0;
            else
                if ((((txGalapagosBridge_V_keep_V_1_state = ap_const_lv2_3) and (txGalapagosBridge_V_keep_V_1_vld_in = ap_const_logic_0) and (txGalapagosBridge_V_keep_V_1_ack_out = ap_const_logic_1)) or ((txGalapagosBridge_V_keep_V_1_state = ap_const_lv2_2) and (txGalapagosBridge_V_keep_V_1_vld_in = ap_const_logic_0)))) then 
                    txGalapagosBridge_V_keep_V_1_state <= ap_const_lv2_2;
                elsif ((((txGalapagosBridge_V_keep_V_1_state = ap_const_lv2_1) and (txGalapagosBridge_TREADY = ap_const_logic_0)) or ((txGalapagosBridge_V_keep_V_1_state = ap_const_lv2_3) and (txGalapagosBridge_TREADY = ap_const_logic_0) and (txGalapagosBridge_V_keep_V_1_vld_in = ap_const_logic_1)))) then 
                    txGalapagosBridge_V_keep_V_1_state <= ap_const_lv2_1;
                elsif ((((txGalapagosBridge_V_keep_V_1_state = ap_const_lv2_1) and (txGalapagosBridge_V_keep_V_1_ack_out = ap_const_logic_1)) or (not(((txGalapagosBridge_V_keep_V_1_vld_in = ap_const_logic_0) and (txGalapagosBridge_V_keep_V_1_ack_out = ap_const_logic_1))) and not(((txGalapagosBridge_TREADY = ap_const_logic_0) and (txGalapagosBridge_V_keep_V_1_vld_in = ap_const_logic_1))) and (txGalapagosBridge_V_keep_V_1_state = ap_const_lv2_3)) or ((txGalapagosBridge_V_keep_V_1_state = ap_const_lv2_2) and (txGalapagosBridge_V_keep_V_1_vld_in = ap_const_logic_1)))) then 
                    txGalapagosBridge_V_keep_V_1_state <= ap_const_lv2_3;
                else 
                    txGalapagosBridge_V_keep_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    txGalapagosBridge_V_last_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                txGalapagosBridge_V_last_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((txGalapagosBridge_V_last_V_1_ack_out = ap_const_logic_1) and (txGalapagosBridge_V_last_V_1_vld_out = ap_const_logic_1))) then 
                                        txGalapagosBridge_V_last_V_1_sel_rd <= not(txGalapagosBridge_V_last_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    txGalapagosBridge_V_last_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                txGalapagosBridge_V_last_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((txGalapagosBridge_V_last_V_1_ack_in = ap_const_logic_1) and (txGalapagosBridge_V_last_V_1_vld_in = ap_const_logic_1))) then 
                                        txGalapagosBridge_V_last_V_1_sel_wr <= not(txGalapagosBridge_V_last_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    txGalapagosBridge_V_last_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                txGalapagosBridge_V_last_V_1_state <= ap_const_lv2_0;
            else
                if ((((txGalapagosBridge_V_last_V_1_state = ap_const_lv2_3) and (txGalapagosBridge_V_last_V_1_vld_in = ap_const_logic_0) and (txGalapagosBridge_V_last_V_1_ack_out = ap_const_logic_1)) or ((txGalapagosBridge_V_last_V_1_state = ap_const_lv2_2) and (txGalapagosBridge_V_last_V_1_vld_in = ap_const_logic_0)))) then 
                    txGalapagosBridge_V_last_V_1_state <= ap_const_lv2_2;
                elsif ((((txGalapagosBridge_V_last_V_1_state = ap_const_lv2_1) and (txGalapagosBridge_TREADY = ap_const_logic_0)) or ((txGalapagosBridge_V_last_V_1_state = ap_const_lv2_3) and (txGalapagosBridge_TREADY = ap_const_logic_0) and (txGalapagosBridge_V_last_V_1_vld_in = ap_const_logic_1)))) then 
                    txGalapagosBridge_V_last_V_1_state <= ap_const_lv2_1;
                elsif ((((txGalapagosBridge_V_last_V_1_state = ap_const_lv2_1) and (txGalapagosBridge_V_last_V_1_ack_out = ap_const_logic_1)) or (not(((txGalapagosBridge_V_last_V_1_vld_in = ap_const_logic_0) and (txGalapagosBridge_V_last_V_1_ack_out = ap_const_logic_1))) and not(((txGalapagosBridge_TREADY = ap_const_logic_0) and (txGalapagosBridge_V_last_V_1_vld_in = ap_const_logic_1))) and (txGalapagosBridge_V_last_V_1_state = ap_const_lv2_3)) or ((txGalapagosBridge_V_last_V_1_state = ap_const_lv2_2) and (txGalapagosBridge_V_last_V_1_vld_in = ap_const_logic_1)))) then 
                    txGalapagosBridge_V_last_V_1_state <= ap_const_lv2_3;
                else 
                    txGalapagosBridge_V_last_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_nbreadreq_fu_52_p5 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_data_V_reg_151 <= lbRxDataIn_TDATA;
                tmp_keep_V_reg_156 <= lbRxDataIn_TKEEP;
                tmp_last_V_reg_161 <= lbRxDataIn_TLAST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_reg_147 <= tmp_nbreadreq_fu_52_p5;
                tmp_reg_147_pp0_iter1_reg <= tmp_reg_147;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((txGalapagosBridge_V_data_V_1_load_A = ap_const_logic_1)) then
                txGalapagosBridge_V_data_V_1_payload_A <= tmp_data_V_reg_151;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((txGalapagosBridge_V_data_V_1_load_B = ap_const_logic_1)) then
                txGalapagosBridge_V_data_V_1_payload_B <= tmp_data_V_reg_151;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((txGalapagosBridge_V_keep_V_1_load_A = ap_const_logic_1)) then
                txGalapagosBridge_V_keep_V_1_payload_A <= tmp_keep_V_reg_156;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((txGalapagosBridge_V_keep_V_1_load_B = ap_const_logic_1)) then
                txGalapagosBridge_V_keep_V_1_payload_B <= tmp_keep_V_reg_156;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((txGalapagosBridge_V_last_V_1_load_A = ap_const_logic_1)) then
                txGalapagosBridge_V_last_V_1_payload_A <= tmp_last_V_reg_161;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((txGalapagosBridge_V_last_V_1_load_B = ap_const_logic_1)) then
                txGalapagosBridge_V_last_V_1_payload_B <= tmp_last_V_reg_161;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start, ap_done_reg, ap_enable_reg_pp0_iter2, lbRxDataIn_TVALID, tmp_nbreadreq_fu_52_p5, txGalapagosBridge_TREADY, txGalapagosBridge_V_data_V_1_state, txGalapagosBridge_V_keep_V_1_state, txGalapagosBridge_V_last_V_1_state)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((txGalapagosBridge_V_last_V_1_state = ap_const_lv2_1) or (txGalapagosBridge_V_keep_V_1_state = ap_const_lv2_1) or (txGalapagosBridge_V_data_V_1_state = ap_const_lv2_1) or ((txGalapagosBridge_V_last_V_1_state = ap_const_lv2_3) and (txGalapagosBridge_TREADY = ap_const_logic_0)) or ((txGalapagosBridge_V_keep_V_1_state = ap_const_lv2_3) and (txGalapagosBridge_TREADY = ap_const_logic_0)) or ((txGalapagosBridge_V_data_V_1_state = ap_const_lv2_3) and (txGalapagosBridge_TREADY = ap_const_logic_0)))) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_nbreadreq_fu_52_p5 = ap_const_lv1_1) and (lbRxDataIn_TVALID = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_done_reg, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, lbRxDataIn_TVALID, tmp_nbreadreq_fu_52_p5, txGalapagosBridge_TREADY, ap_block_state2_io, txGalapagosBridge_V_data_V_1_state, txGalapagosBridge_V_keep_V_1_state, txGalapagosBridge_V_last_V_1_state, ap_block_state3_io)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((txGalapagosBridge_V_last_V_1_state = ap_const_lv2_1) or (txGalapagosBridge_V_keep_V_1_state = ap_const_lv2_1) or (txGalapagosBridge_V_data_V_1_state = ap_const_lv2_1) or (ap_const_boolean_1 = ap_block_state3_io) or ((txGalapagosBridge_V_last_V_1_state = ap_const_lv2_3) and (txGalapagosBridge_TREADY = ap_const_logic_0)) or ((txGalapagosBridge_V_keep_V_1_state = ap_const_lv2_3) and (txGalapagosBridge_TREADY = ap_const_logic_0)) or ((txGalapagosBridge_V_data_V_1_state = ap_const_lv2_3) and (txGalapagosBridge_TREADY = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_io)) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_nbreadreq_fu_52_p5 = ap_const_lv1_1) and (lbRxDataIn_TVALID = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_done_reg, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, lbRxDataIn_TVALID, tmp_nbreadreq_fu_52_p5, txGalapagosBridge_TREADY, ap_block_state2_io, txGalapagosBridge_V_data_V_1_state, txGalapagosBridge_V_keep_V_1_state, txGalapagosBridge_V_last_V_1_state, ap_block_state3_io)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((txGalapagosBridge_V_last_V_1_state = ap_const_lv2_1) or (txGalapagosBridge_V_keep_V_1_state = ap_const_lv2_1) or (txGalapagosBridge_V_data_V_1_state = ap_const_lv2_1) or (ap_const_boolean_1 = ap_block_state3_io) or ((txGalapagosBridge_V_last_V_1_state = ap_const_lv2_3) and (txGalapagosBridge_TREADY = ap_const_logic_0)) or ((txGalapagosBridge_V_keep_V_1_state = ap_const_lv2_3) and (txGalapagosBridge_TREADY = ap_const_logic_0)) or ((txGalapagosBridge_V_data_V_1_state = ap_const_lv2_3) and (txGalapagosBridge_TREADY = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_io)) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_nbreadreq_fu_52_p5 = ap_const_lv1_1) and (lbRxDataIn_TVALID = ap_const_logic_0)))));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start, ap_done_reg, lbRxDataIn_TVALID, tmp_nbreadreq_fu_52_p5)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((tmp_nbreadreq_fu_52_p5 = ap_const_lv1_1) and (lbRxDataIn_TVALID = ap_const_logic_0)));
    end process;


    ap_block_state2_io_assign_proc : process(txGalapagosBridge_V_data_V_1_ack_in, tmp_reg_147)
    begin
                ap_block_state2_io <= ((tmp_reg_147 = ap_const_lv1_1) and (txGalapagosBridge_V_data_V_1_ack_in = ap_const_logic_0));
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_io_assign_proc : process(txGalapagosBridge_V_data_V_1_ack_in, tmp_reg_147_pp0_iter1_reg)
    begin
                ap_block_state3_io <= ((tmp_reg_147_pp0_iter1_reg = ap_const_lv1_1) and (txGalapagosBridge_V_data_V_1_ack_in = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(txGalapagosBridge_TREADY, txGalapagosBridge_V_data_V_1_state, txGalapagosBridge_V_keep_V_1_state, txGalapagosBridge_V_last_V_1_state)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((txGalapagosBridge_V_last_V_1_state = ap_const_lv2_1) or (txGalapagosBridge_V_keep_V_1_state = ap_const_lv2_1) or (txGalapagosBridge_V_data_V_1_state = ap_const_lv2_1) or ((txGalapagosBridge_V_last_V_1_state = ap_const_lv2_3) and (txGalapagosBridge_TREADY = ap_const_logic_0)) or ((txGalapagosBridge_V_keep_V_1_state = ap_const_lv2_3) and (txGalapagosBridge_TREADY = ap_const_logic_0)) or ((txGalapagosBridge_V_data_V_1_state = ap_const_lv2_3) and (txGalapagosBridge_TREADY = ap_const_logic_0)));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to1 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    dest_V_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_nbreadreq_fu_52_p5, lbRxDataIn_TDATA, ap_block_pp0_stage0_01001, dest_V_preg)
    begin
        if (((tmp_nbreadreq_fu_52_p5 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dest_V <= lbRxDataIn_TDATA(31 downto 24);
        else 
            dest_V <= dest_V_preg;
        end if; 
    end process;


    dest_V_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_nbreadreq_fu_52_p5, ap_block_pp0_stage0_11001)
    begin
        if (((tmp_nbreadreq_fu_52_p5 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            dest_V_ap_vld <= ap_const_logic_1;
        else 
            dest_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    id_V_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_nbreadreq_fu_52_p5, lbRxDataIn_TDATA, id_V_preg, ap_block_pp0_stage0_01001)
    begin
        if (((tmp_nbreadreq_fu_52_p5 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            id_V <= lbRxDataIn_TDATA(23 downto 16);
        else 
            id_V <= id_V_preg;
        end if; 
    end process;


    id_V_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_nbreadreq_fu_52_p5, ap_block_pp0_stage0_11001)
    begin
        if (((tmp_nbreadreq_fu_52_p5 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            id_V_ap_vld <= ap_const_logic_1;
        else 
            id_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    lbRxDataIn_TDATA_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, lbRxDataIn_TVALID, tmp_nbreadreq_fu_52_p5, ap_block_pp0_stage0)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (tmp_nbreadreq_fu_52_p5 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            lbRxDataIn_TDATA_blk_n <= lbRxDataIn_TVALID;
        else 
            lbRxDataIn_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    lbRxDataIn_TREADY_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_nbreadreq_fu_52_p5, ap_block_pp0_stage0_11001)
    begin
        if (((tmp_nbreadreq_fu_52_p5 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            lbRxDataIn_TREADY <= ap_const_logic_1;
        else 
            lbRxDataIn_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    size_V_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_nbreadreq_fu_52_p5, ap_block_pp0_stage0_01001, trunc_ln647_fu_142_p1, size_V_preg)
    begin
        if (((tmp_nbreadreq_fu_52_p5 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            size_V <= trunc_ln647_fu_142_p1;
        else 
            size_V <= size_V_preg;
        end if; 
    end process;


    size_V_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tmp_nbreadreq_fu_52_p5, ap_block_pp0_stage0_11001)
    begin
        if (((tmp_nbreadreq_fu_52_p5 = ap_const_lv1_1) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            size_V_ap_vld <= ap_const_logic_1;
        else 
            size_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_nbreadreq_fu_52_p5 <= (0=>(lbRxDataIn_TVALID), others=>'-');
    trunc_ln647_fu_142_p1 <= lbRxDataIn_TDATA(16 - 1 downto 0);
    txGalapagosBridge_TDATA <= txGalapagosBridge_V_data_V_1_data_out;

    txGalapagosBridge_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, tmp_reg_147, txGalapagosBridge_V_data_V_1_state, tmp_reg_147_pp0_iter1_reg, ap_block_pp0_stage0)
    begin
        if ((((tmp_reg_147_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((tmp_reg_147 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            txGalapagosBridge_TDATA_blk_n <= txGalapagosBridge_V_data_V_1_state(1);
        else 
            txGalapagosBridge_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    txGalapagosBridge_TKEEP <= txGalapagosBridge_V_keep_V_1_data_out;
    txGalapagosBridge_TLAST <= txGalapagosBridge_V_last_V_1_data_out;
    txGalapagosBridge_TVALID <= txGalapagosBridge_V_last_V_1_state(0);
    txGalapagosBridge_V_data_V_1_ack_in <= txGalapagosBridge_V_data_V_1_state(1);
    txGalapagosBridge_V_data_V_1_ack_out <= txGalapagosBridge_TREADY;

    txGalapagosBridge_V_data_V_1_data_out_assign_proc : process(txGalapagosBridge_V_data_V_1_payload_A, txGalapagosBridge_V_data_V_1_payload_B, txGalapagosBridge_V_data_V_1_sel)
    begin
        if ((txGalapagosBridge_V_data_V_1_sel = ap_const_logic_1)) then 
            txGalapagosBridge_V_data_V_1_data_out <= txGalapagosBridge_V_data_V_1_payload_B;
        else 
            txGalapagosBridge_V_data_V_1_data_out <= txGalapagosBridge_V_data_V_1_payload_A;
        end if; 
    end process;

    txGalapagosBridge_V_data_V_1_load_A <= (txGalapagosBridge_V_data_V_1_state_cmp_full and not(txGalapagosBridge_V_data_V_1_sel_wr));
    txGalapagosBridge_V_data_V_1_load_B <= (txGalapagosBridge_V_data_V_1_state_cmp_full and txGalapagosBridge_V_data_V_1_sel_wr);
    txGalapagosBridge_V_data_V_1_sel <= txGalapagosBridge_V_data_V_1_sel_rd;
    txGalapagosBridge_V_data_V_1_state_cmp_full <= '0' when (txGalapagosBridge_V_data_V_1_state = ap_const_lv2_1) else '1';

    txGalapagosBridge_V_data_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_reg_147, ap_block_pp0_stage0_11001)
    begin
        if (((tmp_reg_147 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            txGalapagosBridge_V_data_V_1_vld_in <= ap_const_logic_1;
        else 
            txGalapagosBridge_V_data_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    txGalapagosBridge_V_data_V_1_vld_out <= txGalapagosBridge_V_data_V_1_state(0);
    txGalapagosBridge_V_keep_V_1_ack_in <= txGalapagosBridge_V_keep_V_1_state(1);
    txGalapagosBridge_V_keep_V_1_ack_out <= txGalapagosBridge_TREADY;

    txGalapagosBridge_V_keep_V_1_data_out_assign_proc : process(txGalapagosBridge_V_keep_V_1_payload_A, txGalapagosBridge_V_keep_V_1_payload_B, txGalapagosBridge_V_keep_V_1_sel)
    begin
        if ((txGalapagosBridge_V_keep_V_1_sel = ap_const_logic_1)) then 
            txGalapagosBridge_V_keep_V_1_data_out <= txGalapagosBridge_V_keep_V_1_payload_B;
        else 
            txGalapagosBridge_V_keep_V_1_data_out <= txGalapagosBridge_V_keep_V_1_payload_A;
        end if; 
    end process;

    txGalapagosBridge_V_keep_V_1_load_A <= (txGalapagosBridge_V_keep_V_1_state_cmp_full and not(txGalapagosBridge_V_keep_V_1_sel_wr));
    txGalapagosBridge_V_keep_V_1_load_B <= (txGalapagosBridge_V_keep_V_1_state_cmp_full and txGalapagosBridge_V_keep_V_1_sel_wr);
    txGalapagosBridge_V_keep_V_1_sel <= txGalapagosBridge_V_keep_V_1_sel_rd;
    txGalapagosBridge_V_keep_V_1_state_cmp_full <= '0' when (txGalapagosBridge_V_keep_V_1_state = ap_const_lv2_1) else '1';

    txGalapagosBridge_V_keep_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_reg_147, ap_block_pp0_stage0_11001)
    begin
        if (((tmp_reg_147 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            txGalapagosBridge_V_keep_V_1_vld_in <= ap_const_logic_1;
        else 
            txGalapagosBridge_V_keep_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    txGalapagosBridge_V_keep_V_1_vld_out <= txGalapagosBridge_V_keep_V_1_state(0);
    txGalapagosBridge_V_last_V_1_ack_in <= txGalapagosBridge_V_last_V_1_state(1);
    txGalapagosBridge_V_last_V_1_ack_out <= txGalapagosBridge_TREADY;

    txGalapagosBridge_V_last_V_1_data_out_assign_proc : process(txGalapagosBridge_V_last_V_1_payload_A, txGalapagosBridge_V_last_V_1_payload_B, txGalapagosBridge_V_last_V_1_sel)
    begin
        if ((txGalapagosBridge_V_last_V_1_sel = ap_const_logic_1)) then 
            txGalapagosBridge_V_last_V_1_data_out <= txGalapagosBridge_V_last_V_1_payload_B;
        else 
            txGalapagosBridge_V_last_V_1_data_out <= txGalapagosBridge_V_last_V_1_payload_A;
        end if; 
    end process;

    txGalapagosBridge_V_last_V_1_load_A <= (txGalapagosBridge_V_last_V_1_state_cmp_full and not(txGalapagosBridge_V_last_V_1_sel_wr));
    txGalapagosBridge_V_last_V_1_load_B <= (txGalapagosBridge_V_last_V_1_state_cmp_full and txGalapagosBridge_V_last_V_1_sel_wr);
    txGalapagosBridge_V_last_V_1_sel <= txGalapagosBridge_V_last_V_1_sel_rd;
    txGalapagosBridge_V_last_V_1_state_cmp_full <= '0' when (txGalapagosBridge_V_last_V_1_state = ap_const_lv2_1) else '1';

    txGalapagosBridge_V_last_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tmp_reg_147, ap_block_pp0_stage0_11001)
    begin
        if (((tmp_reg_147 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            txGalapagosBridge_V_last_V_1_vld_in <= ap_const_logic_1;
        else 
            txGalapagosBridge_V_last_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    txGalapagosBridge_V_last_V_1_vld_out <= txGalapagosBridge_V_last_V_1_state(0);
end behav;
